import type { DeskItem } from "./types";

// Second shelf. These jobs are not a rename of anyone else's catalogue.
export const deskItemsD: DeskItem[] = [
  {
    id: "202",
    slug: "inclusion-strategy-statement",
    name: "Inclusion strategy statement",
    category: "This term",
    job: "Draft the short public inclusion strategy statement England mainstream schools must publish by 31 December 2026. Commonly occurring needs, barriers, this year's activities with budgeted costs, intended outcomes. Parent-readable. Use only numbers the user supplies. Point them at the current DfE template and Inclusive Mainstream Fund conditions.",
  },
  {
    id: "203",
    slug: "inclusive-mainstream-fund-plan",
    name: "Inclusive Mainstream Fund plan",
    category: "This term",
    job: "Turn the school's IMF allocation into a spend plan that a governor can follow: activity, pupils, cost, what will stop if this is funded, how impact will be checked. Do not invent the allocation. Flag that trustees must scrutinise it.",
  },
  {
    id: "204",
    slug: "report-card-next-steps-plan",
    name: "Report card next-steps plan",
    category: "This term",
    job: "Turn an Ofsted report card (from November 2025) into a short plan against the evaluation areas that need attention or urgent improvement. Keep the inspector's wording visible. No predicted next grade.",
  },
  {
    id: "205",
    slug: "evaluation-area-evidence-map",
    name: "Evaluation-area evidence map",
    category: "This term",
    job: "Sort the school's own evidence under the current school evaluation areas: safeguarding, inclusion, curriculum and teaching, achievement, attendance and behaviour, personal development and wellbeing, leadership and governance, plus early years or post-16 if they apply. Say what is thin. No grade guesses.",
  },
  {
    id: "206",
    slug: "school-profile-page",
    name: "School profile page",
    category: "This term",
    job: "Draft parent-facing profile copy covering attendance, attainment and enrichment from figures the school actually has. Honest. No brochure claims.",
  },
  {
    id: "207",
    slug: "white-paper-implementation-diary",
    name: "White paper implementation diary",
    category: "This term",
    job: "Map what THIS school will do this year, next year and by 2028/29 against the white paper themes the user names. Separate what is already law from what is still consultation or a future duty.",
  },
  {
    id: "208",
    slug: "individual-support-plan-note",
    name: "Individual support plan note",
    category: "This term",
    job: "Help draft a school-level individual support plan from identified need and provision the user lists. This is not an EHCP and must not pretend to be. No extra diagnoses.",
  },
  {
    id: "209",
    slug: "enrichment-entitlement-map",
    name: "Enrichment entitlement map",
    category: "This term",
    job: "Map what this school already offers against the enrichment entitlement the user describes. Gaps, cost, who is missing from the offer.",
  },
  {
    id: "210",
    slug: "children-starting-behind-progress-note",
    name: "Children starting behind, progress note",
    category: "This term",
    job: "Write a board note on progress for pupils who arrived at the next phase behind their peers. Use only the school's own data. Do not invent a national measure that has not been confirmed.",
  },
  {
    id: "211",
    slug: "section-175-audit-return",
    name: "Section 175 audit return",
    category: "Systems and compliance",
    job: "Help complete a section 175 or 157 safeguarding audit from the school's evidence. Mark every answer that still needs the DSL. Conservative. No invented compliance.",
  },
  {
    id: "212",
    slug: "single-central-record-walkthrough",
    name: "Single central record walk-through",
    category: "Systems and compliance",
    job: "Write a checklist and questions for walking the SCR with the person who owns it. What 'complete' looks like. What to do if a line is missing. Not an inspection.",
  },
  {
    id: "213",
    slug: "low-level-concern-note",
    name: "Low-level concern note",
    category: "Staff and personnel",
    job: "Structure a low-level concern record from facts given. Factual language. Do not decide whether it meets the harm threshold. Point to KCSIE and the school's policy.",
  },
  {
    id: "214",
    slug: "lado-referral-holding-note",
    name: "LADO referral holding note",
    category: "Staff and personnel",
    job: "Draft a holding note and internal chronology skeleton when an allegation may need the LADO. Do not investigate in the model. Do not name pupils in the prompt if it can be avoided. The DSL and head own the referral.",
  },
  {
    id: "215",
    slug: "filtering-and-monitoring-review",
    name: "Filtering and monitoring review",
    category: "Systems and compliance",
    job: "Annual review note: what is filtered, who checks logs, how staff report, what was tested this year. Use only the setup the user describes.",
  },
  {
    id: "216",
    slug: "data-breach-72-hour-log",
    name: "Data breach 72-hour log",
    category: "Systems and compliance",
    job: "A decision log for the first 72 hours after a suspected breach. What happened, what data, who is affected, whether ICO or families need telling. The DPO decides. Do not put personal data into the model.",
  },
  {
    id: "217",
    slug: "part-time-timetable-review",
    name: "Part-time timetable review",
    category: "Pupil support",
    job: "Review a reduced timetable. Safeguarding, education entitlement, review date, who agreed it, plan to increase time. Do not treat it as a long-term placement.",
  },
  {
    id: "218",
    slug: "suspension-board-pack",
    name: "Suspension board pack",
    category: "Governance",
    job: "Papers a governing board needs when reviewing a suspension: facts, process followed, pupil voice, parent view, next steps. No invented incident detail. Not legal advice.",
  },
  {
    id: "219",
    slug: "permanent-exclusion-board-pack",
    name: "Permanent exclusion board pack",
    category: "Governance",
    job: "A pack for a governors' exclusion panel from the papers the user lists. Process, evidence index, questions. The panel decides. Do not write the decision.",
  },
  {
    id: "220",
    slug: "managed-move-protocol-note",
    name: "Managed move protocol note",
    category: "Pupil support",
    job: "Plain-English note of how a managed move would work here: consent, trial, review, what happens if it fails. Use the local protocol if pasted.",
  },
  {
    id: "221",
    slug: "alternative-provision-commissioning-brief",
    name: "Alternative provision commissioning brief",
    category: "Pupil support",
    job: "A brief for commissioning AP: why, intended outcomes, hours, safeguarding checks, review. Do not name a provider unless the user did.",
  },
  {
    id: "222",
    slug: "children-missing-education-return",
    name: "Children missing education return",
    category: "Systems and compliance",
    job: "Help complete a CME or off-roll return from facts given. Dates, last known address only if supplied. Flag statutory checks.",
  },
  {
    id: "223",
    slug: "pep-school-contribution",
    name: "PEP school contribution",
    category: "Pupil support",
    job: "Draft the school's contribution to a personal education plan for a looked-after or previously looked-after child. Attainment, attendance, what the school will do this term. Virtual school owns the PEP.",
  },
  {
    id: "224",
    slug: "fair-access-case-note",
    name: "Fair Access case note",
    category: "Systems and compliance",
    job: "A short case note for a Fair Access Protocol meeting. Facts the school can stand behind. No campaign language.",
  },
  {
    id: "225",
    slug: "three-year-budget-recovery",
    name: "Three-year budget recovery",
    category: "Governance",
    job: "A recovery narrative from the figures supplied: structural gap, options, what gets protected, risks to pupils. Do not invent balances or ICFP ratios.",
  },
  {
    id: "226",
    slug: "falling-rolls-options-paper",
    name: "Falling rolls options paper",
    category: "Governance",
    job: "Options when numbers are falling: class structure, mixed age, staffing, PAN. Costs only if supplied. Name the human cost of each option.",
  },
  {
    id: "227",
    slug: "condition-bid-narrative",
    name: "Condition bid narrative",
    category: "Systems and compliance",
    job: "Narrative for a condition, CIF or similar estates bid. Problem, risk if we wait, pupil impact, cost. No invented survey findings.",
  },
  {
    id: "228",
    slug: "school-based-nursery-case",
    name: "School-based nursery case",
    category: "This term",
    job: "A case for opening or expanding a school-based nursery. Places, staffing, estate, wraparound. Do not invent capital.",
  },
  {
    id: "229",
    slug: "wraparound-and-breakfast-plan",
    name: "Wraparound and breakfast plan",
    category: "This term",
    job: "Plan breakfast or wraparound the school can actually staff. Hours, charging, FSM, who is missed.",
  },
  {
    id: "230",
    slug: "related-party-transaction-note",
    name: "Related party transaction note",
    category: "Governance",
    job: "A plain note for trustees when a related party transaction is proposed. Who is related, what is being bought, how value for money will be shown. Not legal advice.",
  },
  {
    id: "231",
    slug: "internal-scrutiny-programme",
    name: "Internal scrutiny programme",
    category: "Governance",
    job: "A light-touch annual internal scrutiny programme for a small trust. Few areas, real testing, report to the audit committee.",
  },
  {
    id: "232",
    slug: "scheme-of-delegation-change-paper",
    name: "Scheme of delegation change paper",
    category: "Governance",
    job: "A board paper to change who decides what. Current rule, proposed rule, why, what could go wrong.",
  },
  {
    id: "233",
    slug: "industrial-action-contingency",
    name: "Industrial action contingency",
    category: "Staff and personnel",
    job: "A contingency note for notified industrial action. Opening decision, supervision, comms, exams if relevant. Respect lawful action. Not a strike-breaking plan.",
  },
  {
    id: "234",
    slug: "inset-day-that-earns-its-hours",
    name: "INSET day that earns its hours",
    category: "Staff and personnel",
    job: "Design one INSET day around a real school problem. Timing, input, practice, what staff leave able to do. No death-by-slides.",
  },
  {
    id: "235",
    slug: "mobile-phone-policy-refresh",
    name: "Mobile phone policy refresh",
    category: "Systems and compliance",
    job: "Refresh the pupil phone policy from current DfE expectations and how this school actually works. Consistency, exceptions, sanctions that staff will use.",
  },
  {
    id: "236",
    slug: "uniform-cost-review",
    name: "Uniform cost review",
    category: "Systems and compliance",
    job: "Review branded items, second-hand provision and total cost for a family. Propose cuts that still look like this school.",
  },
  {
    id: "237",
    slug: "rshe-parental-consultation-pack",
    name: "RSHE parental consultation pack",
    category: "Communication",
    job: "A consultation pack for RSHE or relationships education. What is taught, when parents can withdraw, how to comment. Calm. Statutory bits flagged for the user to check.",
  },
  {
    id: "238",
    slug: "results-day-comms-pack",
    name: "Results day comms pack",
    category: "Communication",
    job: "Staff briefing, parent message and holding lines for results day. No predicted percentages.",
  },
  {
    id: "239",
    slug: "critical-incident-first-hour",
    name: "Critical incident first hour",
    category: "Systems and compliance",
    job: "A first-hour log and role card after a critical incident. Who is told, who is not, what is written down. No operational detail that would help someone cause harm.",
  },
  {
    id: "240",
    slug: "bereavement-community-message",
    name: "Bereavement community message",
    category: "Communication",
    job: "A short message to staff, pupils or families after a death. Warm, factual, no speculation. Point to support the school actually has.",
  },
  {
    id: "241",
    slug: "staff-ai-use-note",
    name: "Staff AI use note",
    category: "This term",
    job: "A one-page note for staff: what they may put into a model, what they must not, when a person still signs the work. Point to the DPO and the school's own policy. Not a vendor pitch.",
  },
  {
    id: "242",
    slug: "assessment-integrity-with-ai",
    name: "Assessment integrity with AI",
    category: "This term",
    job: "A short staff and pupil note on coursework and generative AI. What help is allowed, what is not, how the school will check. Phase-specific.",
  },
  {
    id: "243",
    slug: "board-skills-audit",
    name: "Board skills audit",
    category: "Governance",
    job: "A skills audit the board will actually complete. Few questions. What it means for recruitment, not a decorative heatmap.",
  },
  {
    id: "244",
    slug: "chair-and-head-one-to-one",
    name: "Chair and head one-to-one",
    category: "Governance",
    job: "An agenda for the regular chair and head meeting. Strategy, risk, wellbeing, what must not wait for the full board.",
  },
  {
    id: "245",
    slug: "pan-consultation-response",
    name: "PAN consultation response",
    category: "Systems and compliance",
    job: "A school or trust response to a published admission number consultation. Facts about rooms, staffing and local places. No territorial language.",
  },
  {
    id: "246",
    slug: "newly-arrived-pupil-welcome",
    name: "Newly arrived pupil welcome",
    category: "Pupil support",
    job: "First days and first half-term for a newly arrived or refugee pupil. Language, timetable, named adult, what staff need before day one.",
  },
  {
    id: "247",
    slug: "young-carer-support-note",
    name: "Young carer support note",
    category: "Pupil support",
    job: "A support note when a pupil is a young carer. Attendance flexibility, homework, named adult. Do not invent home circumstances.",
  },
  {
    id: "248",
    slug: "exam-contingency-day-plan",
    name: "Exam contingency day plan",
    category: "Day to day",
    job: "What the school does if an exam cannot run as planned. Rooms, staffing, JCQ or awarding-body checks the exams officer must confirm.",
  },
  {
    id: "249",
    slug: "visit-emergency-card",
    name: "Visit emergency card",
    category: "Day to day",
    job: "A one-page card for the visit leader and the base contact. Who to call, what to write down, when to close the trip. No invented medical protocols.",
  },
  {
    id: "250",
    slug: "severe-weather-decision-note",
    name: "Severe weather decision note",
    category: "Day to day",
    job: "A decision note for opening, partial opening or closing. Who decides, who is told, exam days, vulnerable pupils. Record the reason.",
  },
];
