import type { DeskItem } from "./types";

// GCSE schemes and revision maps. Never invent a spec, set text, paper or topic list.
export const deskItemsG: DeskItem[] = [
  {
    id: "343",
    slug: "gcse-scheme-of-work-generator",
    name: "GCSE scheme of work generator",
    category: "GCSE",
    job: "Build a scheme of work from the specification the user pastes. Board, spec code, tier, hours per week, start and exam dates. Units in spec order unless they ask otherwise. Assessment points. Do not add topics that are not in the pasted spec.",
  },
  {
    id: "344",
    slug: "two-year-ks4-scheme",
    name: "Two-year KS4 scheme",
    category: "GCSE",
    job: "A Year 10 and Year 11 map from the pasted spec. What must be taught by the first mock. What is left for Year 11. Built-in retrieval. Flag NEA deadlines if the spec has them.",
  },
  {
    id: "345",
    slug: "half-term-sow-from-spec",
    name: "Half-term SOW from the spec",
    category: "GCSE",
    job: "One half term only. Lessons that fit the periods given. Objective, core knowledge, practice, exit check. Homework that does not need a specialist adult at home.",
  },
  {
    id: "346",
    slug: "gcse-revision-programme",
    name: "GCSE revision programme",
    category: "GCSE",
    job: "A revision programme from today to the first paper date the user names. Weekly focus, retrieval, past-paper practice only if they have papers. Separate class time from home time.",
  },
  {
    id: "347",
    slug: "gcse-paper-by-paper-revision",
    name: "Paper-by-paper revision",
    category: "GCSE",
    job: "One plan per paper from the pasted spec. What that paper actually tests. Timing. The mistakes this class already makes, if the user listed them.",
  },
  {
    id: "348",
    slug: "gcse-nea-timeline",
    name: "GCSE NEA timeline",
    category: "GCSE",
    job: "A non-exam assessment timeline from the spec and centre dates. What pupils do, what the teacher may say, checkpoints. Not a way to write the work for them.",
  },
  {
    id: "349",
    slug: "gcse-english-language-map",
    name: "GCSE English Language map",
    category: "GCSE",
    job: "Scheme and revision map for English Language. Papers, timings and AOs from the pasted spec only. Reading and writing practice that matches those papers. No invented inserts.",
  },
  {
    id: "350",
    slug: "gcse-english-literature-map",
    name: "GCSE English Literature map",
    category: "GCSE",
    job: "Scheme and revision map for Literature. Use only the set texts and poems the user names. Paper structure from the pasted spec. Quotation, whole-text and comparison practice. Do not invent a set text list.",
  },
  {
    id: "351",
    slug: "gcse-maths-map",
    name: "GCSE Maths map",
    category: "GCSE",
    job: "Scheme and revision map for Maths. Foundation or Higher as named. Topic list from the pasted spec. Calculator and non-calculator papers. Weak-topic first if the user gave mock data.",
  },
  {
    id: "352",
    slug: "gcse-combined-science-map",
    name: "GCSE Combined Science map",
    category: "GCSE",
    job: "Scheme and revision map for Combined Science (Trilogy or Synergy as named). Biology, chemistry and physics units from the pasted spec. Required practicals only if listed. Foundation or Higher.",
  },
  {
    id: "353",
    slug: "gcse-biology-map",
    name: "GCSE Biology map",
    category: "GCSE",
    job: "Scheme and revision map for separate Biology. Topics and required practicals from the pasted spec. Paper split as the spec states. No invented content from Combined Science.",
  },
  {
    id: "354",
    slug: "gcse-chemistry-map",
    name: "GCSE Chemistry map",
    category: "GCSE",
    job: "Scheme and revision map for separate Chemistry. Topics and required practicals from the pasted spec. Equations and calculations only where the spec asks.",
  },
  {
    id: "355",
    slug: "gcse-physics-map",
    name: "GCSE Physics map",
    category: "GCSE",
    job: "Scheme and revision map for separate Physics. Topics, equations and required practicals from the pasted spec. Higher-tier only content marked as such.",
  },
  {
    id: "356",
    slug: "gcse-history-map",
    name: "GCSE History map",
    category: "GCSE",
    job: "Scheme and revision map for History. Use only the studies and sites the user names. Question types from the pasted spec. No extra periods.",
  },
  {
    id: "357",
    slug: "gcse-geography-map",
    name: "GCSE Geography map",
    category: "GCSE",
    job: "Scheme and revision map for Geography. Themes, fieldwork and issue evaluation from the pasted spec. Named case studies only if the user supplied them.",
  },
  {
    id: "358",
    slug: "gcse-french-map",
    name: "GCSE French map",
    category: "GCSE",
    job: "Scheme and revision map for French. Themes, skills and tiers from the pasted spec. For awards after June 2026 use the vocabulary and grammar lists the user pastes. Do not invent a vocab list.",
  },
  {
    id: "359",
    slug: "gcse-german-map",
    name: "GCSE German map",
    category: "GCSE",
    job: "Scheme and revision map for German. Same rules as French. Paste the current spec and the 2026 vocabulary and grammar lists if that is the award year.",
  },
  {
    id: "360",
    slug: "gcse-spanish-map",
    name: "GCSE Spanish map",
    category: "GCSE",
    job: "Scheme and revision map for Spanish. Same rules as French. Paste the current spec and the 2026 vocabulary and grammar lists if that is the award year.",
  },
  {
    id: "361",
    slug: "gcse-mfl-other-map",
    name: "GCSE other language map",
    category: "GCSE",
    job: "Scheme and revision map for any other GCSE language the user names (Italian, Urdu, Mandarin, Arabic, Polish, Latin, and so on). Build only from the pasted spec. Speaking, listening, reading, writing as that spec sets them.",
  },
  {
    id: "362",
    slug: "gcse-computer-science-map",
    name: "GCSE Computer Science map",
    category: "GCSE",
    job: "Scheme and revision map for Computer Science. Theory papers and programming from the pasted spec. Languages only if the centre named one.",
  },
  {
    id: "363",
    slug: "gcse-religious-studies-map",
    name: "GCSE Religious Studies map",
    category: "GCSE",
    job: "Scheme and revision map for RS. Religions and themes the user names, from the pasted spec. Short course if they said so. No invented beliefs.",
  },
  {
    id: "364",
    slug: "gcse-business-map",
    name: "GCSE Business map",
    category: "GCSE",
    job: "Scheme and revision map for Business. Units and calculation skills from the pasted spec. Case-study practice without inventing a paper.",
  },
  {
    id: "365",
    slug: "gcse-citizenship-map",
    name: "GCSE Citizenship map",
    category: "GCSE",
    job: "Scheme and revision map for Citizenship Studies. Themes and the taking-citizenship-action requirement from the pasted spec.",
  },
  {
    id: "366",
    slug: "gcse-pe-map",
    name: "GCSE PE map",
    category: "GCSE",
    job: "Scheme and revision map for PE. Theory papers, NEA and sports from the pasted spec and the sports this centre actually assesses. Do not invent practical marks.",
  },
  {
    id: "367",
    slug: "gcse-food-map",
    name: "GCSE Food Preparation and Nutrition map",
    category: "GCSE",
    job: "Scheme and revision map for Food. Theory and NEA tasks from the pasted spec. Food safety flagged. No invented recipes as if they were assessed dishes.",
  },
  {
    id: "368",
    slug: "gcse-dt-map",
    name: "GCSE Design and Technology map",
    category: "GCSE",
    job: "Scheme and revision map for D&T. Core technical principles, specialist material and NEA from the pasted spec and the material this class actually uses.",
  },
  {
    id: "369",
    slug: "gcse-art-map",
    name: "GCSE Art and Design map",
    category: "GCSE",
    job: "Scheme and revision map for Art and Design. Endorsement the user names (fine art, photography, textiles, 3D, graphics, craft). Component structure from the pasted spec. Portfolio checkpoints, not a style to copy.",
  },
  {
    id: "370",
    slug: "gcse-drama-map",
    name: "GCSE Drama map",
    category: "GCSE",
    job: "Scheme and revision map for Drama. Set text and live performance only if named. Components from the pasted spec. Devising timeline that fits this centre.",
  },
  {
    id: "371",
    slug: "gcse-music-map",
    name: "GCSE Music map",
    category: "GCSE",
    job: "Scheme and revision map for Music. Areas of study, set works and NEA from the pasted spec. Set works only if the user listed them.",
  },
  {
    id: "372",
    slug: "gcse-dance-map",
    name: "GCSE Dance map",
    category: "GCSE",
    job: "Scheme and revision map for Dance. Anthology works and NEA from the pasted spec. Works only if named.",
  },
  {
    id: "373",
    slug: "gcse-media-map",
    name: "GCSE Media Studies map",
    category: "GCSE",
    job: "Scheme and revision map for Media. Close-study products from the list the user pastes. Components from the spec. Do not invent CSPs.",
  },
  {
    id: "374",
    slug: "gcse-sociology-map",
    name: "GCSE Sociology map",
    category: "GCSE",
    job: "Scheme and revision map for Sociology. Topics and studies from the pasted spec. Named studies only if supplied.",
  },
  {
    id: "375",
    slug: "gcse-psychology-map",
    name: "GCSE Psychology map",
    category: "GCSE",
    job: "Scheme and revision map for Psychology. Topics, studies and research methods from the pasted spec. No extra studies.",
  },
  {
    id: "376",
    slug: "gcse-statistics-map",
    name: "GCSE Statistics map",
    category: "GCSE",
    job: "Scheme and revision map for Statistics. Collection, processing, representation and probability from the pasted spec. Foundation or Higher.",
  },
  {
    id: "377",
    slug: "gcse-ancient-history-map",
    name: "GCSE Ancient History map",
    category: "GCSE",
    job: "Scheme and revision map for Ancient History. Period and depth studies the user names, from the pasted spec.",
  },
  {
    id: "378",
    slug: "gcse-classics-latin-map",
    name: "GCSE Latin or Classical Civilisation map",
    category: "GCSE",
    job: "Scheme and revision map for Latin or Classical Civilisation as named. Set texts and topics from the pasted spec only.",
  },
  {
    id: "379",
    slug: "gcse-astronomy-geology-map",
    name: "GCSE Astronomy or Geology map",
    category: "GCSE",
    job: "Scheme and revision map for Astronomy or Geology as named. Topics and observational or fieldwork requirements from the pasted spec.",
  },
  {
    id: "380",
    slug: "level-2-further-maths-map",
    name: "Level 2 Further Maths map",
    category: "GCSE",
    job: "Scheme and revision map for AQA Level 2 Further Maths or the equivalent the user names. Topics from the pasted spec. This is not GCSE Maths Higher with extra questions.",
  },
];
