import type { DeskItem } from "./types";

export const deskItemsA: DeskItem[] = [
  {
    id: "001",
    slug: "long-range-school-plan",
    name: "Long-range school plan",
    category: "School improvement",
    job: "Produce a 3 to 5 year plan with vision, priorities, success measures, owners and a yearly phasing. Keep it usable by governors, not a brochure.",
  },
  {
    id: "002",
    slug: "academy-conversion-briefing",
    name: "Academy conversion briefing",
    category: "Governance",
    job: "Set out arguments for and against conversion or joining a trust for THIS school. Separate facts, values and risks. Do not recommend a vote.",
  },
  {
    id: "003",
    slug: "accessibility-plan-draft",
    name: "Accessibility plan draft",
    category: "Systems and compliance",
    job: "Draft an Accessibility Plan covering curriculum, physical environment and information, with timescales and owners. Flag statutory bits the user must check.",
  },
  {
    id: "004",
    slug: "white-paper-response-note",
    name: "White paper response note",
    category: "School improvement",
    job: "Map the school's current work against the latest schools white paper themes the user names. Do not invent policy that was not provided.",
  },
  {
    id: "005",
    slug: "admissions-appeal-statement",
    name: "Admissions appeal statement",
    category: "Systems and compliance",
    job: "Draft a school statement for an independent appeal panel. Stick to published admission arrangements and facts supplied. No pressure language.",
  },
  {
    id: "006",
    slug: "allergy-healthcare-plan",
    name: "Allergy healthcare plan",
    category: "Pupil support",
    job: "Draft an Individual Healthcare Plan for allergy. Medical detail only from the user. Never invent dosages, emergency drugs or contacts.",
  },
  {
    id: "007",
    slug: "assembly-script",
    name: "Assembly script",
    category: "Day to day",
    job: "Write an assembly script for the age range given, tied to the school's values if supplied. Keep it short enough to deliver.",
  },
  {
    id: "008",
    slug: "attendance-code-explainer",
    name: "Attendance code explainer",
    category: "Systems and compliance",
    job: "Suggest which attendance code may apply and why, in plain English. Say this is not legal advice and the school must check current DfE attendance guidance.",
  },
  {
    id: "009",
    slug: "whole-school-attendance-plan",
    name: "Whole-school attendance plan",
    category: "School improvement",
    job: "Draft a whole-school attendance plan from the data the user pastes. Name barriers, actions, owners and review points. No fake benchmarks.",
  },
  {
    id: "010",
    slug: "attendance-message",
    name: "Attendance message",
    category: "Communication",
    job: "Write a parent-facing attendance message in the channel asked for (text, email, letter, call script). Warm and clear. No shame.",
  },
  {
    id: "011",
    slug: "pupil-attendance-plan",
    name: "Pupil attendance plan",
    category: "Pupil support",
    job: "Draft a plan for one pupil or family from the facts given. Practical, kind, reviewable.",
  },
  {
    id: "012",
    slug: "meeting-notes-from-a-transcript",
    name: "Meeting notes from a transcript",
    category: "Day to day",
    job: "The model cannot hear audio. Ask the user to paste a transcript (Whisper/local STT). Then clean it into notes with actions and owners.",
  },
  {
    id: "013",
    slug: "audit-follow-up-plan",
    name: "Audit follow-up plan",
    category: "School improvement",
    job: "Turn a RAG audit or visit note into an action plan. Keep the original findings visible. Do not upgrade a Red to Green.",
  },
  {
    id: "014",
    slug: "award-application-draft",
    name: "Award application draft",
    category: "Communication",
    job: "Write an evidence-led award narrative from the examples the user supplies. No invented impact figures.",
  },
  {
    id: "015",
    slug: "behaviour-examples-bank",
    name: "Behaviour examples bank",
    category: "Staff and personnel",
    job: "Turn the school's behaviour policy into concrete examples of expected conduct by age, for staff to use consistently.",
  },
  {
    id: "016",
    slug: "behaviour-incident-note",
    name: "Behaviour incident note",
    category: "Pupil support",
    job: "Structure an incident record from facts given. Do not invent witnesses, times or sanctions. Use factual language.",
  },
  {
    id: "017",
    slug: "pupil-behaviour-support-plan",
    name: "Pupil behaviour support plan",
    category: "Pupil support",
    job: "Draft a support plan, not a punishment sheet. Include triggers, adult responses, teaching of the skill, and review.",
  },
  {
    id: "018",
    slug: "funding-bid-draft",
    name: "Funding bid draft",
    category: "Communication",
    job: "Write a bid from the funder's criteria and the school's evidence. Mark every claim that still needs a number.",
  },
  {
    id: "019",
    slug: "book-look-feedback",
    name: "Book look feedback",
    category: "School improvement",
    job: "Write developmental feedback from the scrutiny notes provided. Separate what was seen from what is inferred.",
  },
  {
    id: "020",
    slug: "school-business-case",
    name: "School business case",
    category: "Systems and compliance",
    job: "Draft a business case: problem, options, cost, benefit, risk, recommendation. Do not invent costs.",
  },
  {
    id: "021",
    slug: "application-shortlist-note",
    name: "Application shortlist note",
    category: "Staff and personnel",
    job: "Summarise applications against the person spec only. Flag gaps. Do not infer protected characteristics or 'culture fit'.",
  },
  {
    id: "022",
    slug: "impact-case-study",
    name: "Impact case study",
    category: "School improvement",
    job: "Write a case study from the evidence supplied. Before/after only if the user gave numbers.",
  },
  {
    id: "023",
    slug: "change-plan",
    name: "Change plan",
    category: "Staff and personnel",
    job: "Build a change plan: why, who is affected, what will be different by when, how staff are involved, how you will know.",
  },
  {
    id: "024",
    slug: "character-reference-draft",
    name: "Character reference draft",
    category: "Staff and personnel",
    job: "Draft a reference from facts the writer actually knows. Never invent dates of employment or unstated qualities.",
  },
  {
    id: "025",
    slug: "open-leadership-scratch-pad",
    name: "Open leadership scratch pad",
    category: "For you",
    job: "Be a careful thinking partner for a UK school leader. Ask for missing context. Do not pretend to be an inspector or solicitor.",
  },
  {
    id: "026",
    slug: "job-checklist",
    name: "Job checklist",
    category: "Day to day",
    job: "Make a checklist for the job described. Order it the way the work actually happens.",
  },
  {
    id: "027",
    slug: "climate-action-plan",
    name: "Climate action plan",
    category: "Systems and compliance",
    job: "Draft a school climate action plan. Use only duties and data the user provides. Practical actions over slogans.",
  },
  {
    id: "028",
    slug: "climate-plan-health-check",
    name: "Climate plan health check",
    category: "Systems and compliance",
    job: "Audit a draft climate plan the user pastes. Strengths, gaps, what a board would still ask.",
  },
  {
    id: "029",
    slug: "grow-coaching-notes",
    name: "GROW coaching notes",
    category: "For you",
    job: "Run a GROW coaching conversation. Ask one good question at a time. Do not take over the goal.",
  },
  {
    id: "030",
    slug: "staff-code-of-conduct-draft",
    name: "Staff code of conduct draft",
    category: "Staff and personnel",
    job: "Draft a staff code of conduct in plain English. Mark statutory or KCSIE-linked sections the user must check.",
  },
  {
    id: "031",
    slug: "peer-visit-write-up",
    name: "Peer visit write-up",
    category: "School improvement",
    job: "Turn visit notes into a short collaborative write-up: what was seen, questions, agreed next step.",
  },
  {
    id: "032",
    slug: "collective-worship-outline",
    name: "Collective worship outline",
    category: "Day to day",
    job: "Write a collective worship outline. Respect the school's designation if given. Do not invent legal requirements.",
  },
  {
    id: "033",
    slug: "leadership-doubt-worksheet",
    name: "Leadership doubt worksheet",
    category: "For you",
    job: "Help a leader examine a specific doubt with evidence from their own practice. No therapy claims.",
  },
  {
    id: "034",
    slug: "message-tone-check",
    name: "Message tone check",
    category: "Communication",
    job: "Analyse a draft message for tone, clarity, risk and likely reading by parents or staff. Suggest a rewrite.",
  },
  {
    id: "035",
    slug: "plain-english-rewrite",
    name: "Plain English rewrite",
    category: "Communication",
    job: "Rewrite for the reading age or audience given. Keep the meaning. Short sentences. UK English.",
  },
  {
    id: "036",
    slug: "complaint-reply-draft",
    name: "Complaint reply draft",
    category: "Communication",
    job: "Draft a complaint response from the facts and policy the user pastes. Acknowledge, set out findings, say what happens next. No defensiveness.",
  },
  {
    id: "037",
    slug: "complaint-letter-draft",
    name: "Complaint letter draft",
    category: "Communication",
    job: "Help a leader draft a formal complaint they need to send. Factual, dated, specific about the remedy sought.",
  },
  {
    id: "038",
    slug: "process-crib-sheet",
    name: "Process crib sheet",
    category: "Day to day",
    job: "Turn a process into a one-page crib sheet a busy adult can follow.",
  },
  {
    id: "039",
    slug: "critical-friend-critique",
    name: "Critical friend critique",
    category: "For you",
    job: "Critique a plan or paper as a well-informed critical friend. Be specific. Offer a tighter version.",
  },
  {
    id: "040",
    slug: "csed-self-evaluation",
    name: "CSED self-evaluation",
    category: "School improvement",
    job: "Help structure a Catholic school evaluation document from the evidence supplied. Do not invent diocesan judgements.",
  },
  {
    id: "041",
    slug: "cultural-capital-note",
    name: "Cultural capital note",
    category: "School improvement",
    job: "Describe how THIS school's offer builds knowledge and experience, using only what the user lists. Avoid cliché lists.",
  },
  {
    id: "042",
    slug: "curriculum-review-note",
    name: "Curriculum review note",
    category: "School improvement",
    job: "Analyse a curriculum outline the user pastes. Sequence, gaps, assessment, workload. Phase-specific.",
  },
  {
    id: "043",
    slug: "progression-map-draft",
    name: "Progression map draft",
    category: "School improvement",
    job: "Draft a progression map for the subject and years given. Show what gets more complex, not just new topics.",
  },
  {
    id: "044",
    slug: "curriculum-rationale",
    name: "Curriculum rationale",
    category: "School improvement",
    job: "Write a short rationale: why this content, in this order, for these pupils.",
  },
  {
    id: "045",
    slug: "cyber-incident-plan",
    name: "Cyber incident plan",
    category: "Systems and compliance",
    job: "Draft an incident response plan. Include who to call, what to isolate, what to tell staff and families. No fake vendor names.",
  },
  {
    id: "046",
    slug: "subject-deep-dive-pack",
    name: "Subject deep-dive pack",
    category: "School improvement",
    job: "Build a subject leader briefing pack from the evidence supplied. Questions they may be asked. Answers only where evidence exists.",
  },
  {
    id: "047",
    slug: "hard-conversation-plan",
    name: "Hard conversation plan",
    category: "Staff and personnel",
    job: "Plan a difficult conversation: purpose, opening line, facts, likely reactions, close. Not a script to trap someone.",
  },
  {
    id: "048",
    slug: "hard-meeting-brief",
    name: "Hard meeting brief",
    category: "Day to day",
    job: "Prepare the leader for a difficult meeting. Agenda, aims, risks, fallback.",
  },
  {
    id: "049",
    slug: "investigation-report-skeleton",
    name: "Investigation report skeleton",
    category: "Staff and personnel",
    job: "Turn investigation notes into a structured report skeleton. Do not decide guilt. Do not invent evidence. Say HR and policy must lead.",
  },
  {
    id: "050",
    slug: "paper-interrogation",
    name: "Paper interrogation",
    category: "Day to day",
    job: "Read the pasted document and answer the user's questions. Quote the line you are relying on.",
  },
  {
    id: "051",
    slug: "two-draft-comparison",
    name: "Two-draft comparison",
    category: "Day to day",
    job: "Compare two pasted texts. List what changed, what vanished, what that might mean.",
  },
  {
    id: "052",
    slug: "document-qanda",
    name: "Document Q&A",
    category: "Day to day",
    job: "Answer questions using only the pasted document. If it is not in the text, say so.",
  },
  {
    id: "053",
    slug: "paper-summary",
    name: "Paper summary",
    category: "Day to day",
    job: "Summarise the pasted paper for the audience named (board, staff, parents). Keep numbers accurate.",
  },
  {
    id: "054",
    slug: "early-help-plan-draft",
    name: "Early Help plan draft",
    category: "Pupil support",
    job: "Draft an Early Help plan from family and school facts given. Do not diagnose. Signpost, do not replace the local process.",
  },
  {
    id: "055",
    slug: "ect-progress-note",
    name: "ECT progress note",
    category: "Staff and personnel",
    job: "Draft an ECT mentor or induction note from observations supplied. ECF language only if the user wants it.",
  },
  {
    id: "056",
    slug: "ehcp-review-meeting-pack",
    name: "EHCP review meeting pack",
    category: "SEND and inclusion",
    job: "Prepare annual review notes from the EHCP and school evidence pasted. Do not rewrite the EHCP as if you were the LA.",
  },
  {
    id: "057",
    slug: "ehcp-panel-speaking-note",
    name: "EHCP panel speaking note",
    category: "SEND and inclusion",
    job: "Write a five-minute speaking note for a panel. Only needs and provision that appear in the user's evidence.",
  },
  {
    id: "058",
    slug: "send-provision-map",
    name: "SEND provision map",
    category: "SEND and inclusion",
    job: "Build a provision map table from the interventions the school actually runs. No off-the-shelf shopping list.",
  },
  {
    id: "059",
    slug: "ehcp-school-support-plan",
    name: "EHCP school support plan",
    category: "SEND and inclusion",
    job: "Turn EHCP outcomes into a school-level plan staff can follow this term.",
  },
  {
    id: "060",
    slug: "child-friendly-ehcp-targets",
    name: "Child-friendly EHCP targets",
    category: "SEND and inclusion",
    job: "Rewrite outcomes as child-friendly targets with what 'good' looks like. Keep the original outcome beside them.",
  },
  {
    id: "061",
    slug: "ehcp-pen-portrait",
    name: "EHCP pen portrait",
    category: "SEND and inclusion",
    job: "Write a pen portrait and key-need summary from the plan pasted. No extra diagnoses.",
  },
  {
    id: "062",
    slug: "ehcp-transition-suggestions",
    name: "EHCP transition suggestions",
    category: "SEND and inclusion",
    job: "Suggest updates the school may take to the next review because of a transition. Suggestions only.",
  },
  {
    id: "063",
    slug: "staff-or-parent-email",
    name: "Staff or parent email",
    category: "Communication",
    job: "Write the email. Subject line, body, sign-off. Match the tone asked for.",
  },
  {
    id: "064",
    slug: "enrichment-plan",
    name: "Enrichment plan",
    category: "School improvement",
    job: "Plan enrichment that this school can actually staff and fund.",
  },
  {
    id: "065",
    slug: "equality-information-draft",
    name: "Equality information draft",
    category: "Systems and compliance",
    job: "Draft public-sector equality duty information from the data supplied. Do not invent group outcomes.",
  },
  {
    id: "066",
    slug: "equality-objectives-draft",
    name: "Equality objectives draft",
    category: "Systems and compliance",
    job: "Propose measurable equality objectives from the school's own evidence.",
  },
  {
    id: "067",
    slug: "ethos-and-values-page",
    name: "Ethos and values page",
    category: "Communication",
    job: "Write ethos and values copy that sounds like this school, using the phrases they already use.",
  },
  {
    id: "068",
    slug: "one-page-executive-summary",
    name: "One-page executive summary",
    category: "Communication",
    job: "Compress the pasted paper to one page. Decisions and numbers first.",
  },
  {
    id: "069",
    slug: "exit-interview-write-up",
    name: "Exit interview write-up",
    category: "Staff and personnel",
    job: "Turn exit interview notes into themes and actions. Protect anonymity. No gossip.",
  },
  {
    id: "070",
    slug: "eyfs-action-plan",
    name: "EYFS action plan",
    category: "School improvement",
    job: "Draft an EYFS plan against the EYFS framework themes the user names. Practical for the setting type.",
  }
];
