import type { DeskItem } from "./types";

// Primary KS1 and KS2. Paste the programme of study or the school's own curriculum. Do not invent content or SAT papers.
export const deskItemsK: DeskItem[] = [
  {
    id: "545",
    slug: "ks1-two-year-scheme",
    name: "KS1 two-year scheme",
    category: "Primary",
    job: "A Year 1 and Year 2 scheme from the pasted programme of study or the school's own curriculum. What must be secure by the end of Year 2. Do not turn Year 1 into a SAT year.",
  },
  {
    id: "546",
    slug: "ks2-four-year-scheme",
    name: "KS2 four-year scheme",
    category: "Primary",
    job: "A Year 3 to Year 6 scheme from the pasted programme of study. Lower and upper KS2 marked. What must be secure before Year 6 tests if this school sits them.",
  },
  {
    id: "547",
    slug: "lower-ks2-scheme",
    name: "Lower KS2 scheme",
    category: "Primary",
    job: "A Year 3 and Year 4 scheme from the pasted curriculum. The jump from KS1 named if the user listed it. Fluency before complexity.",
  },
  {
    id: "548",
    slug: "upper-ks2-scheme",
    name: "Upper KS2 scheme",
    category: "Primary",
    job: "A Year 5 and Year 6 scheme from the pasted curriculum. Test technique only in the window the school actually uses. The rest of the curriculum still exists.",
  },
  {
    id: "549",
    slug: "year-1-scheme",
    name: "Year 1 scheme",
    category: "Primary",
    job: "One year of Year 1 from the pasted curriculum. First half term that settles them after Reception. Phonics as the school names the programme. Play and desks in a ratio this class can bear.",
  },
  {
    id: "550",
    slug: "year-2-scheme",
    name: "Year 2 scheme",
    category: "Primary",
    job: "One year of Year 2 from the pasted curriculum. Optional KS1 tests only if the school uses them and said so. Writing that is not a genre conveyor belt.",
  },
  {
    id: "551",
    slug: "year-3-scheme",
    name: "Year 3 scheme",
    category: "Primary",
    job: "One year of Year 3 from the pasted curriculum. What Year 2 left unfinished if named. Independence without pretending they are Year 5.",
  },
  {
    id: "552",
    slug: "year-4-scheme",
    name: "Year 4 scheme",
    category: "Primary",
    job: "One year of Year 4 from the pasted curriculum. Multiplication tables check only as this school runs it. The rest of the year is still a curriculum.",
  },
  {
    id: "553",
    slug: "year-5-scheme",
    name: "Year 5 scheme",
    category: "Primary",
    job: "One year of Year 5 from the pasted curriculum. Depth before Year 6 acceleration. New content the programme of study actually places here.",
  },
  {
    id: "554",
    slug: "year-6-scheme",
    name: "Year 6 scheme",
    category: "Primary",
    job: "One year of Year 6 from the pasted curriculum. What is taught before May and what is taught after. Secondary-ready habits, not a three-month test camp unless the user asked for that.",
  },
  {
    id: "555",
    slug: "mixed-age-primary-scheme",
    name: "Mixed-age primary scheme",
    category: "Primary",
    job: "A scheme for the mixed-age class the user named (for example Year 3/4). Same lessons, two pitch points. Cycle A and cycle B if they said the school uses them.",
  },
  {
    id: "556",
    slug: "reception-to-year-1-curriculum",
    name: "Reception to Year 1 curriculum",
    category: "Primary",
    job: "The first half term of Year 1 from what Reception actually did. Continuous provision that shrinks on purpose. Phonics as named. No invented ELG scores.",
  },
  {
    id: "557",
    slug: "year-2-to-year-3-bridge",
    name: "Year 2 to Year 3 bridge",
    category: "Primary",
    job: "A first half term in Year 3 that uses the Year 2 handover the user pasted. Reading stamina, number facts, how they write. Do not invent KS1 results.",
  },
  {
    id: "558",
    slug: "year-6-to-year-7-handover",
    name: "Year 6 to Year 7 handover",
    category: "Primary",
    job: "A handover note from the Year 6 teacher to secondary. Reading, writing, maths, how they learn, what must not be lost. Facts only. No predicted KS3 pathway.",
  },
  {
    id: "559",
    slug: "primary-english-map",
    name: "Primary English map",
    category: "Primary",
    job: "A KS1 or KS2 English map from the pasted programme of study and the texts this school actually uses. Reading, writing, spoken language. Do not invent a reading spine.",
  },
  {
    id: "560",
    slug: "primary-phonics-from-ssp",
    name: "Phonics from the named programme",
    category: "Primary",
    job: "A phonics sequence from the SSP the school named and any overview they pasted. Revisit, teach, practise, apply. Do not invent programme steps or alien words.",
  },
  {
    id: "561",
    slug: "primary-reading-lesson",
    name: "Primary reading lesson",
    category: "Primary",
    job: "One reading lesson from the text and focus the user named. Vocabulary, a stretch of text, talk, a short written or oral response. Age of the class as given.",
  },
  {
    id: "562",
    slug: "primary-writing-unit",
    name: "Primary writing unit",
    category: "Primary",
    job: "A writing unit from the purpose and audience the user named. Model, shared, independent. Grammar only as it serves this piece. No invented WAGOLL if they did not paste one.",
  },
  {
    id: "563",
    slug: "primary-gps-without-the-mill",
    name: "Grammar that serves writing",
    category: "Primary",
    job: "A short grammar sequence from the year-group content pasted. Taught so it turns up in writing, not only in a test booklet.",
  },
  {
    id: "564",
    slug: "phonics-check-parent-note",
    name: "Phonics screening parent note",
    category: "Primary",
    job: "A parent note on the Year 1 phonics screening check. What it is, when it is, what happens if they retake in Year 2. No score predictions.",
  },
  {
    id: "565",
    slug: "reading-for-pleasure-plan",
    name: "Reading for pleasure plan",
    category: "Primary",
    job: "A half-term plan that protects reading for pleasure. Class reader, library time, how adults talk about books. Titles only if the user listed them.",
  },
  {
    id: "566",
    slug: "primary-maths-map",
    name: "Primary maths map",
    category: "Primary",
    job: "A KS1 or KS2 maths map from the pasted programme of study. Number first. The year-group objectives in an order this school can teach.",
  },
  {
    id: "567",
    slug: "primary-maths-unit",
    name: "Primary maths unit",
    category: "Primary",
    job: "One maths unit from the objectives pasted. Fluency, reasoning, problem solving. Concrete and pictorial only as this classroom actually has them.",
  },
  {
    id: "568",
    slug: "times-tables-check-plan",
    name: "Multiplication tables check plan",
    category: "Primary",
    job: "A Year 4 plan for the multiplication tables check from how this school already practises tables. Short, frequent. The rest of maths still happens.",
  },
  {
    id: "569",
    slug: "primary-science-map",
    name: "Primary science map",
    category: "Primary",
    job: "A KS1 or KS2 science map from the pasted programme of study. Working scientifically. Practicals this classroom can actually run.",
  },
  {
    id: "570",
    slug: "primary-history-map",
    name: "Primary history map",
    category: "Primary",
    job: "A primary history map from the pasted programme of study and the periods this school teaches. Chronology across the years. No extra topics.",
  },
  {
    id: "571",
    slug: "primary-geography-map",
    name: "Primary geography map",
    category: "Primary",
    job: "A primary geography map from the pasted programme of study. Locational knowledge, places, fieldwork only if the school named the sites.",
  },
  {
    id: "572",
    slug: "primary-art-map",
    name: "Primary art map",
    category: "Primary",
    job: "A primary art map from the pasted curriculum. Disciplines and artists only if named. Materials this stock cupboard has.",
  },
  {
    id: "573",
    slug: "primary-music-map",
    name: "Primary music map",
    category: "Primary",
    job: "A primary music map from the pasted curriculum. Singing, listening, composing. Instruments only if the school has them.",
  },
  {
    id: "574",
    slug: "primary-pe-map",
    name: "Primary PE map",
    category: "Primary",
    job: "A primary PE map from the pasted programme of study, including swimming if the school runs it. Indoor backup. No invented fixtures.",
  },
  {
    id: "575",
    slug: "primary-computing-map",
    name: "Primary computing map",
    category: "Primary",
    job: "A primary computing map from the pasted programme of study. Computer science, IT and digital literacy as the school splits them. Software only if named.",
  },
  {
    id: "576",
    slug: "primary-dt-map",
    name: "Primary design and technology map",
    category: "Primary",
    job: "A primary D and T map from the pasted programme of study. Cooking and nutrition if that sits here. Tools this school actually lets children use.",
  },
  {
    id: "577",
    slug: "primary-languages-map",
    name: "Primary languages map",
    category: "Primary",
    job: "A KS2 languages map for the language this school teaches. From the pasted programme of study or scheme. Do not invent a word list. KS1 only if they asked.",
  },
  {
    id: "578",
    slug: "primary-re-map",
    name: "Primary RE map",
    category: "Primary",
    job: "A primary RE map from the locally agreed syllabus or the academy curriculum pasted. Religions and worldviews only as listed. Right of withdrawal flagged.",
  },
  {
    id: "579",
    slug: "primary-relationships-health-map",
    name: "Primary relationships and health map",
    category: "Primary",
    job: "A map for relationships and health education from the school's policy and the statutory content pasted. Age-appropriate. Sex education only if this school teaches it and the user said so.",
  },
  {
    id: "580",
    slug: "primary-assessment-calendar",
    name: "Primary assessment calendar",
    category: "Primary",
    job: "An assessment calendar for the year named. Phonics check, MTC, KS2 tests only if this school sits them. Teacher assessment that is not a spreadsheet religion.",
  },
  {
    id: "581",
    slug: "primary-moderation-pack",
    name: "Primary writing moderation pack",
    category: "Primary",
    job: "A moderation pack for writing from the criteria and samples the user pasted. What good looks like this year. No invented TAFs.",
  },
  {
    id: "582",
    slug: "ks2-test-week-brief",
    name: "KS2 test week staff brief",
    category: "Primary",
    job: "A staff brief for KS2 test week from the timetable pasted. Rooms, readers, rest breaks, who is calm. Access arrangements only as listed. Check current STA guidance.",
  },
  {
    id: "583",
    slug: "ks2-results-parent-note",
    name: "KS2 results parent note",
    category: "Primary",
    job: "A parent note that explains scaled scores from the results the school will actually send. What the number means. What it does not. No league-table commentary.",
  },
  {
    id: "584",
    slug: "primary-knowledge-organiser",
    name: "Primary knowledge organiser",
    category: "Primary",
    job: "A one-page organiser for the unit named, from the pasted curriculum only. Vocabulary children will actually say. No extra facts for show.",
  },
  {
    id: "585",
    slug: "primary-homework-that-fits",
    name: "Primary homework that fits a family",
    category: "Primary",
    job: "A half-term homework cycle. Reading, number facts, one short task. Work that does not need a craft shop or a parent who trained as a teacher.",
  },
  {
    id: "586",
    slug: "primary-send-in-the-scheme",
    name: "SEND in the primary scheme",
    category: "Primary",
    job: "Adapt a pasted primary scheme for the needs listed. Same curriculum. Access, not a parallel course. No invented diagnoses.",
  },
  {
    id: "587",
    slug: "primary-cover-proof-scheme",
    name: "Primary cover-proof scheme",
    category: "Primary",
    job: "Rewrite a primary scheme so another adult can run the desk lessons. Flag practicals, swimming, trips and anything that must not run without the class teacher.",
  },
  {
    id: "588",
    slug: "primary-catch-up-reading",
    name: "Primary catch-up reading",
    category: "Primary",
    job: "A catch-up plan from the reading evidence pasted. Minutes per week as given. Keep it inside the school's phonics or reading programme if named. No invented reading ages.",
  },
  {
    id: "589",
    slug: "primary-catch-up-number",
    name: "Primary catch-up number",
    category: "Primary",
    job: "A catch-up plan from the number gaps listed. Secure the facts the next unit needs. Short, daily if the timetable allows.",
  },
  {
    id: "590",
    slug: "primary-parents-curriculum-note",
    name: "Primary curriculum note for parents",
    category: "Primary",
    job: "A plain note for families on what this term covers and how they can help at home. No shopping list of workbooks.",
  },
  {
    id: "591",
    slug: "primary-report-comment-bank",
    name: "Primary report comment bank",
    category: "Primary",
    job: "A short comment bank for this year group and subject. Strength, next step, how to help at home. No invented children. Teacher still picks the line.",
  },
  {
    id: "592",
    slug: "primary-enquiry-or-theme",
    name: "Primary enquiry or theme",
    category: "Primary",
    job: "One enquiry or theme from the question the user named. Subject contributions only where they are honest. Outcome a child this age can actually make.",
  },
  {
    id: "593",
    slug: "primary-outdoor-or-trip",
    name: "Primary outdoor learning or trip",
    category: "Primary",
    job: "A plan for outdoor learning or a trip from the site and aims given. Risks the user must confirm. Learning that is not a worksheet on a clipboard.",
  },
  {
    id: "594",
    slug: "primary-subject-lead-intent",
    name: "Primary subject-lead intent",
    category: "Primary",
    job: "A one-page intent for this subject from what the school already believes and the programme of study pasted. Plain English. Not an Ofsted performance.",
  },
  {
    id: "595",
    slug: "primary-any-subject-fallback",
    name: "Any other primary subject",
    category: "Primary",
    job: "A scheme and unit map for a primary subject the shelf does not name. Build only from the pasted curriculum. If they did not paste one, stop and ask.",
  },
];
