import type { DeskItem } from "./types";

// Classroom and tutor desk. Not a leadership catalogue with the serial numbers filed off.
export const deskItemsE: DeskItem[] = [
  {
    id: "251",
    slug: "lesson-plan-for-this-class",
    name: "Lesson plan for this class",
    category: "Classroom",
    job: "Plan one lesson for the class described. Objective, prior knowledge, the task, adaptive teaching, how you will know it landed. Time it so it fits the period. No invented pupils.",
  },
  {
    id: "252",
    slug: "five-lesson-sequence",
    name: "Five-lesson sequence",
    category: "Classroom",
    job: "A five-lesson sequence for the unit named. What gets harder each lesson. Retrieval from last time. Assessment point. Workload-honest resources.",
  },
  {
    id: "253",
    slug: "cover-work-pack",
    name: "Cover work pack",
    category: "Classroom",
    job: "Work a cover teacher or cover supervisor can run without the specialist. Clear instructions, timing, what to collect, what 'finished' looks like.",
  },
  {
    id: "254",
    slug: "ta-briefing-for-this-lesson",
    name: "TA briefing for this lesson",
    category: "Classroom",
    job: "A short briefing for the teaching assistant before the lesson. Who to sit with, the scaffold, what not to do for the pupil, how to feed back at the end.",
  },
  {
    id: "255",
    slug: "adaptive-teaching-notes",
    name: "Adaptive teaching notes",
    category: "Classroom",
    job: "How this lesson changes for the pupils named, from facts given. Scaffold, adult support, alternative task. Not three worksheets labelled bronze silver gold unless that is how this school works.",
  },
  {
    id: "256",
    slug: "scaffold-for-this-task",
    name: "Scaffold for this task",
    category: "Classroom",
    job: "Build a scaffold for the task pasted: sentence stems, worked example, checklist. Say when the scaffold comes off.",
  },
  {
    id: "257",
    slug: "stretch-for-high-prior-attainers",
    name: "Stretch for high prior attainers",
    category: "Classroom",
    job: "An extension that is harder thinking, not more of the same. Tied to this lesson's objective.",
  },
  {
    id: "258",
    slug: "eal-support-in-this-lesson",
    name: "EAL support in this lesson",
    category: "Classroom",
    job: "Language support for this lesson from the pupil's stage as described. Key vocabulary, visuals, what the pupil will say or write. No invented proficiency level.",
  },
  {
    id: "259",
    slug: "send-adaptations-this-week",
    name: "SEND adaptations this week",
    category: "Classroom",
    job: "What this teacher will actually change this week for the pupils listed. From the plan or EHCP excerpts pasted. Classroom-level. Not a rewrite of the plan.",
  },
  {
    id: "260",
    slug: "retrieval-quiz",
    name: "Retrieval quiz",
    category: "Classroom",
    job: "A short retrieval quiz from the content taught. Mix of last lesson, last week, last term if the user says so. Answers on a second block.",
  },
  {
    id: "261",
    slug: "knowledge-organiser",
    name: "Knowledge organiser",
    category: "Classroom",
    job: "One page. Core knowledge for the unit. Definitions a pupil can revise. No wallpaper quotes.",
  },
  {
    id: "262",
    slug: "model-answer-wagoll",
    name: "Model answer",
    category: "Classroom",
    job: "A model response at the standard named, with a short 'why this works' for the class. Age-appropriate. Mark the bits that are non-negotiable.",
  },
  {
    id: "263",
    slug: "whole-class-feedback",
    name: "Whole-class feedback",
    category: "Classroom",
    job: "Feedback from a set of books or papers as described. What most got, three misconceptions, the reteach task. No fake quotes from pupils.",
  },
  {
    id: "264",
    slug: "marking-comment-bank",
    name: "Marking comment bank",
    category: "Classroom",
    job: "Short comments for this assignment. Strength, next step. Specific to the criteria. Not 'good work keep it up'.",
  },
  {
    id: "265",
    slug: "live-marking-codes",
    name: "Live marking codes",
    category: "Classroom",
    job: "A small code sheet this teacher can use while circulating. Few codes. What the pupil does when they see each one.",
  },
  {
    id: "266",
    slug: "homework-that-fits",
    name: "Homework that fits",
    category: "Classroom",
    job: "Homework this class can do without a specialist adult at home. Time estimate. How it will be checked. What happens if it is not done.",
  },
  {
    id: "267",
    slug: "six-week-intervention-plan",
    name: "Six-week intervention plan",
    category: "Classroom",
    job: "A short intervention for the gap named. Who, how often, the resource, how you will know after six weeks. Do not invent a published programme.",
  },
  {
    id: "268",
    slug: "guided-reading-questions",
    name: "Guided reading questions",
    category: "Classroom",
    job: "Questions for the text named, in the order you would ask them. Retrieval, inference, vocabulary. Age given by the user.",
  },
  {
    id: "269",
    slug: "phonics-group-notes",
    name: "Phonics group notes",
    category: "Classroom",
    job: "Notes for a phonics group from the code and stage the user names. Revisit, teach, practise, apply. No invented scheme steps.",
  },
  {
    id: "270",
    slug: "practical-lesson-risk-note",
    name: "Practical lesson risk note",
    category: "Classroom",
    job: "Hazards and controls for THIS practical, from the activity described. Do not invent CLEAPSS codes or chemical quantities.",
  },
  {
    id: "271",
    slug: "walking-talking-mock",
    name: "Walking-talking mock",
    category: "Classroom",
    job: "A script for walking a class through a paper. Timing, where marks hide, common traps. Use only the paper or mark scheme pasted.",
  },
  {
    id: "272",
    slug: "class-revision-plan",
    name: "Class revision plan",
    category: "Classroom",
    job: "A revision plan for this class between now and the date given. What to revisit, what to drop, a realistic homework load.",
  },
  {
    id: "273",
    slug: "predicted-grade-rationale",
    name: "Predicted grade rationale",
    category: "Classroom",
    job: "A short rationale for a predicted or working-at grade from the evidence listed. Honest. No comfort grades.",
  },
  {
    id: "274",
    slug: "access-arrangements-classroom-evidence",
    name: "Access arrangements classroom evidence",
    category: "Classroom",
    job: "What this teacher has seen in class that may support an access arrangements file. Facts only. The SENCo owns the application.",
  },
  {
    id: "275",
    slug: "transition-notes-to-next-teacher",
    name: "Transition notes to the next teacher",
    category: "Classroom",
    job: "A handover for the next teacher. What works, what does not, reading ages or groups if supplied. No gossip. No diagnoses you were not given.",
  },
  {
    id: "276",
    slug: "parents-evening-talking-points",
    name: "Parents' evening talking points",
    category: "Classroom",
    job: "Five minutes of talking points for each pupil listed, from the notes pasted. Start with strength. One precise next step. No surprises that should have been a call.",
  },
  {
    id: "277",
    slug: "class-newsletter",
    name: "Class newsletter",
    category: "Classroom",
    job: "A short class update. What we learned, what is coming, how families can help without buying a laminator.",
  },
  {
    id: "278",
    slug: "praise-postcard",
    name: "Praise postcard",
    category: "Classroom",
    job: "A specific postcard or note home. Name the behaviour or the piece of work. Not a personality prize.",
  },
  {
    id: "279",
    slug: "phone-call-home-script",
    name: "Phone call home",
    category: "Classroom",
    job: "Prepare a call home. Opening line, the fact, the ask, close. Warm if it is good news. Calm if it is not.",
  },
  {
    id: "280",
    slug: "restoration-after-my-lesson",
    name: "Restoration after my lesson",
    category: "Classroom",
    job: "A conversation after something went wrong in this teacher's lesson. Facts, impact, what happens tomorrow. Not a script to trap the pupil.",
  },
  {
    id: "281",
    slug: "duty-incident-note",
    name: "Duty incident note",
    category: "Classroom",
    job: "A factual note from break, lunch or corridor duty. What was seen, who was told, first aid if given. Do not invent witnesses.",
  },
  {
    id: "282",
    slug: "safeguarding-concern-to-dsl",
    name: "Safeguarding concern to the DSL",
    category: "Classroom",
    job: "Help a teacher write a concern for the DSL from facts they give. Child's words in quotation marks if supplied. No analysis beyond what was seen or said. Do not investigate. The DSL owns next steps.",
  },
  {
    id: "283",
    slug: "visit-group-leader-card",
    name: "Visit group-leader card",
    category: "Classroom",
    job: "A card for the teacher leading a group on a visit. Headcount, meeting point, who to call, medical notes only if the user pasted them.",
  },
  {
    id: "284",
    slug: "local-walk-risk-note",
    name: "Local walk risk note",
    category: "Classroom",
    job: "A short risk note for a walk in the locality described. Roads, ratios, weather. Do not invent the school's visits policy.",
  },
  {
    id: "285",
    slug: "ect-weekly-reflection",
    name: "ECT weekly reflection",
    category: "Classroom",
    job: "A weekly reflection an ECT can take to their mentor. What they taught, what landed, one thing to try. Their voice, not a polished essay.",
  },
  {
    id: "286",
    slug: "teacher-appraisal-evidence-log",
    name: "Teacher appraisal evidence log",
    category: "Classroom",
    job: "Turn the teacher's notes into an evidence log against the objectives given. Dates and artefacts only if supplied.",
  },
  {
    id: "287",
    slug: "what-the-learning-walk-should-see",
    name: "What the learning walk should see",
    category: "Classroom",
    job: "A one-side note a teacher can use before a walk: the focus, what is already in books, the question they hope is asked. Honest about the weak bit.",
  },
  {
    id: "288",
    slug: "my-books-before-scrutiny",
    name: "My books before scrutiny",
    category: "Classroom",
    job: "A self-check against the school's book expectations, from what the teacher says is in the books. Gaps to fix this week, not a defence.",
  },
  {
    id: "289",
    slug: "trainee-lesson-plan",
    name: "Trainee lesson plan",
    category: "Classroom",
    job: "A lesson plan a trainee can defend. Mentor notes in the margin: what to watch, when to step in. Do not write it as if the trainee already taught it.",
  },
  {
    id: "290",
    slug: "after-school-club-session",
    name: "After-school club session",
    category: "Classroom",
    job: "One club session. Arrival, activity, how it ends, ratios. Fun that still has an adult in charge.",
  },
  {
    id: "291",
    slug: "form-time-sequence",
    name: "Form time sequence",
    category: "Form tutor",
    job: "A two-week form-time sequence that fits the minutes you actually have. Register, notices, one useful activity. No fake PSHE scheme.",
  },
  {
    id: "292",
    slug: "tutor-attendance-conversation",
    name: "Tutor attendance conversation",
    category: "Form tutor",
    job: "Prepare a tutor conversation about attendance with the pupil or family facts given. Curious, not shaming. One next step.",
  },
  {
    id: "293",
    slug: "daily-report-comments",
    name: "Daily report comments",
    category: "Form tutor",
    job: "Short lesson-by-lesson comments for a daily report card. Factual. What improved.",
  },
  {
    id: "294",
    slug: "tutor-evening-notes",
    name: "Tutor evening notes",
    category: "Form tutor",
    job: "Notes for a tutor evening: attendance, conduct, the story across subjects from the data pasted. One family action.",
  },
  {
    id: "295",
    slug: "year-group-assembly-from-a-tutor",
    name: "Year-group assembly from a tutor",
    category: "Form tutor",
    job: "An assembly a tutor can deliver to a year group. Short enough to stand up and do. Tied to the theme given.",
  },
  {
    id: "296",
    slug: "leaver-comment",
    name: "Leaver comment",
    category: "Form tutor",
    job: "A leaver comment or yearbook line from what the tutor actually knows. Specific. No empty 'will go far'.",
  },
  {
    id: "297",
    slug: "tutor-report-paragraph",
    name: "Tutor report paragraph",
    category: "Form tutor",
    job: "One tutor paragraph for the report cycle. Attendance, attitude, the person in the form. Age-appropriate.",
  },
  {
    id: "298",
    slug: "form-group-charter",
    name: "Form group charter",
    category: "Form tutor",
    job: "A short charter the form can live with. Few lines. Written so pupils could have said them.",
  },
  {
    id: "299",
    slug: "missed-homework-tutor-note",
    name: "Missed homework tutor note",
    category: "Form tutor",
    job: "A tutor note or message when homework keeps not arriving. Check barriers first. Then the school sanction if that is the policy.",
  },
  {
    id: "300",
    slug: "new-arrival-in-my-form",
    name: "New arrival in my form",
    category: "Form tutor",
    job: "The first fortnight for a pupil new to the form. Buddy, map, who to eat with, what the tutor checks on day three and day ten.",
  },
];
