import type { DeskItem } from "./types";

export const deskItemsC: DeskItem[] = [
  {
    id: "141",
    slug: "progress-meeting-pack",
    name: "Progress meeting pack",
    category: "Staff and personnel",
    role: "a school leader dealing with staff",
    gate: false,
    guidance: [],
    job: "Prepare a PPM pack: which pupils, why, questions, possible actions.",
  },
  {
    id: "142",
    slug: "child-protection-plan-school-actions",
    name: "Child protection plan school actions",
    category: "Pupil support",
    role: "a pastoral lead",
    gate: false,
    guidance: ["Keeping children safe in education 2026 (in force 1 September 2026, England), the section you are using."],
    job: "Help the school set out ITS actions under a child protection or child-in-need plan. Safeguarding lead owns it. No invented case detail.",
  },
  {
    id: "143",
    slug: "reintegration-plan",
    name: "Reintegration plan",
    category: "Pupil support",
    role: "a pastoral lead",
    gate: false,
    guidance: ["School suspensions and permanent exclusions (DfE, updated 26 July 2026, England)."],
    job: "Plan a return from exclusion or alternative provision. Timetable, adults, review.",
  },
  {
    id: "144",
    slug: "report-comment-check",
    name: "Report comment check",
    category: "Communication",
    role: "a member of school staff",
    gate: false,
    guidance: [],
    job: "Check pasted report comments for tone, accuracy, cliché and anything that should not go home.",
  },
  {
    id: "145",
    slug: "rapid-improvement-plan",
    name: "Rapid improvement plan",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "A short, sharp plan for the next 6 to 12 weeks. Few priorities. Visible measures.",
  },
  {
    id: "146",
    slug: "re-action-plan",
    name: "RE action plan",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "Subject action plan for RE, including locally agreed syllabus if named.",
  },
  {
    id: "147",
    slug: "employment-reference-draft",
    name: "Employment reference draft",
    category: "Staff and personnel",
    role: "a school leader dealing with staff",
    gate: false,
    guidance: [],
    job: "Draft a reference from facts the referee can stand behind. Separate fact from opinion.",
  },
  {
    id: "148",
    slug: "leadership-responsibility-map",
    name: "Leadership responsibility map",
    category: "Staff and personnel",
    role: "a school leader dealing with staff",
    gate: false,
    guidance: [],
    job: "Map roles and accountabilities so the same job is not owned by three people and none.",
  },
  {
    id: "149",
    slug: "risk-assessment-draft",
    name: "Risk assessment draft",
    category: "Systems and compliance",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "Draft a risk assessment. Hazard, who, existing control, extra control, residual. Do not invent residual scores if the school has a matrix.",
  },
  {
    id: "150",
    slug: "risk-register-rows",
    name: "Risk register rows",
    category: "Governance",
    role: "someone preparing a paper for governors or trustees",
    gate: false,
    guidance: [],
    job: "Write risk register rows for the risks the user names. Cause, effect, control, owner, review.",
  },
  {
    id: "151",
    slug: "assessment-rubric",
    name: "Assessment rubric",
    category: "Day to day",
    role: "a member of school staff",
    gate: false,
    guidance: [],
    job: "Build a rubric with clear columns. Age-appropriate language.",
  },
  {
    id: "152",
    slug: "staff-training-scenario",
    name: "Staff training scenario",
    category: "Staff and personnel",
    role: "a school leader dealing with staff",
    gate: false,
    guidance: [],
    job: "Write a training scenario with a dilemma and debrief questions. No real pupil details.",
  },
  {
    id: "153",
    slug: "scheme-of-delegation-explainer",
    name: "Scheme of delegation explainer",
    category: "Governance",
    role: "someone preparing a paper for governors or trustees",
    gate: false,
    guidance: [],
    job: "Explain a pasted scheme of delegation in plain English: who decides what.",
  },
  {
    id: "154",
    slug: "sef-from-notes",
    name: "SEF from notes",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "Turn notes into a SEF-style evaluation against the framework the user names. Judgement language only if they insist, and label it as the school's view.",
  },
  {
    id: "155",
    slug: "fe-self-assessment-draft",
    name: "FE self-assessment draft",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "Same job for further education, using the FE framework the user names.",
  },
  {
    id: "156",
    slug: "sef-strengths-and-next-steps",
    name: "SEF strengths and next steps",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "A short strengths / next steps page from evidence, not from hope.",
  },
  {
    id: "157",
    slug: "send-action-plan",
    name: "SEND action plan",
    category: "SEND and inclusion",
    role: "a SENCO or inclusion lead",
    gate: false,
    guidance: ["The plan and the school's SEND policy. Do not treat the 2015 SEND code of practice as if this pack had rewritten it."],
    job: "Plan SEND improvement from the school's own audit. Workload-aware.",
  },
  {
    id: "158",
    slug: "send-consultation-reply",
    name: "SEND consultation reply",
    category: "SEND and inclusion",
    role: "a SENCO or inclusion lead",
    gate: false,
    guidance: ["The plan and the school's SEND policy. Do not treat the 2015 SEND code of practice as if this pack had rewritten it."],
    job: "Draft a response to a local or national SEND consultation from the school's experience.",
  },
  {
    id: "159",
    slug: "send-form-helper",
    name: "SEND form helper",
    category: "SEND and inclusion",
    role: "a SENCO or inclusion lead",
    gate: false,
    guidance: ["The plan and the school's SEND policy. Do not treat the 2015 SEND code of practice as if this pack had rewritten it."],
    job: "Help complete a named SEND form from evidence pasted. Keep the form's own headings.",
  },
  {
    id: "160",
    slug: "send-joiner-induction",
    name: "SEND joiner induction",
    category: "SEND and inclusion",
    role: "a SENCO or inclusion lead",
    gate: false,
    guidance: ["The plan and the school's SEND policy. Do not treat the 2015 SEND code of practice as if this pack had rewritten it."],
    job: "Induction plan for a pupil with SEND, including what staff need before day one.",
  },
  {
    id: "161",
    slug: "send-support-plan",
    name: "SEND support plan",
    category: "SEND and inclusion",
    role: "a SENCO or inclusion lead",
    gate: false,
    guidance: ["The plan and the school's SEND policy. Do not treat the 2015 SEND code of practice as if this pack had rewritten it."],
    job: "School-based SEND support plan. Assess, plan, do, review.",
  },
  {
    id: "162",
    slug: "send-report-rewrite",
    name: "SEND report rewrite",
    category: "SEND and inclusion",
    role: "a SENCO or inclusion lead",
    gate: false,
    guidance: ["The plan and the school's SEND policy. Do not treat the 2015 SEND code of practice as if this pack had rewritten it."],
    job: "Rewrite a specialist report into language class staff can use, without dropping the meaning.",
  },
  {
    id: "163",
    slug: "sexual-harassment-school-checklist",
    name: "Sexual harassment school checklist",
    category: "Systems and compliance",
    role: "a school leader",
    gate: false,
    guidance: ["Keeping children safe in education 2026 (in force 1 September 2026, England), the section you are using."],
    job: "A practical checklist and comms outline for schools. KCSIE-aware. Not a full legal pack. Point the user at current statutory guidance.",
  },
  {
    id: "164",
    slug: "siams-action-plan",
    name: "SIAMS action plan",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "Action plan for a church school from SIAMS findings or self-evaluation the user pastes.",
  },
  {
    id: "165",
    slug: "siams-self-evaluation-draft",
    name: "SIAMS self-evaluation draft",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "Draft SIAMS self-evaluation from the evidence supplied. Do not invent theological claims.",
  },
  {
    id: "166",
    slug: "school-improvement-plan-draft",
    name: "School improvement plan draft",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "Draft a SIP: few priorities, success criteria, actions, owners, cost, evaluation. Tie to the SEF if pasted.",
  },
  {
    id: "167",
    slug: "school-social-posts",
    name: "School social posts",
    category: "Communication",
    role: "a member of school staff",
    gate: false,
    guidance: [],
    job: "Write posts. No pupil photos implied. Check consent reminder at the end.",
  },
  {
    id: "168",
    slug: "speech-draft",
    name: "Speech draft",
    category: "Communication",
    role: "a member of school staff",
    gate: false,
    guidance: [],
    job: "Write a speech for the occasion and length given. Readable aloud.",
  },
  {
    id: "169",
    slug: "pe-and-sport-premium-report",
    name: "PE and sport premium report",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "Draft the PE and sport premium statement from spend and impact the user lists.",
  },
  {
    id: "170",
    slug: "appraisal-review-write-up",
    name: "Appraisal review write-up",
    category: "Staff and personnel",
    role: "a school leader dealing with staff",
    gate: false,
    guidance: [],
    job: "Write an appraisal review from objectives and evidence supplied. Balanced.",
  },
  {
    id: "171",
    slug: "staff-handbook-section",
    name: "Staff handbook section",
    category: "Staff and personnel",
    role: "a school leader dealing with staff",
    gate: false,
    guidance: [],
    job: "Write or refresh handbook sections. Plain English. Point to the policy, do not duplicate it all.",
  },
  {
    id: "172",
    slug: "staff-induction-plan",
    name: "Staff induction plan",
    category: "Staff and personnel",
    role: "a school leader dealing with staff",
    gate: false,
    guidance: ["Keeping children safe in education 2026 (in force 1 September 2026, England), the section you are using."],
    job: "A first-term induction plan. Safeguarding first. Who they meet. What 'ready' looks like.",
  },
  {
    id: "173",
    slug: "staff-meeting-agenda",
    name: "Staff meeting agenda",
    category: "Day to day",
    role: "a member of school staff",
    gate: false,
    guidance: [],
    job: "Agenda, timing, pre-read, the one decision. Protect teacher time.",
  },
  {
    id: "174",
    slug: "staff-knowledge-quiz",
    name: "Staff knowledge quiz",
    category: "Day to day",
    role: "a member of school staff",
    gate: false,
    guidance: [],
    job: "A short quiz on a policy or training theme, with answers on a second block.",
  },
  {
    id: "175",
    slug: "staff-recognition-note",
    name: "Staff recognition note",
    category: "Communication",
    role: "a member of school staff",
    gate: false,
    guidance: [],
    job: "Write a specific shout-out. Name the behaviour, not a personality trait.",
  },
  {
    id: "176",
    slug: "staff-support-plan",
    name: "Staff support plan",
    category: "Staff and personnel",
    role: "a school leader dealing with staff",
    gate: false,
    guidance: [],
    job: "A support plan, not a capability ambush. Actions for the person and the school.",
  },
  {
    id: "177",
    slug: "staff-wellbeing-plan",
    name: "Staff wellbeing plan",
    category: "Staff and personnel",
    role: "a school leader dealing with staff",
    gate: false,
    guidance: [],
    job: "Wellbeing actions that change workload or control, not just fruit and yoga.",
  },
  {
    id: "178",
    slug: "standards-letter-draft",
    name: "Standards letter draft",
    category: "Communication",
    role: "a member of school staff",
    gate: false,
    guidance: [],
    job: "Draft a standards or expectations letter. Clear, respectful, specific.",
  },
  {
    id: "179",
    slug: "workload-and-stress-note",
    name: "Workload and stress note",
    category: "For you",
    role: "the person using this prompt",
    gate: false,
    guidance: [],
    job: "Help a leader sort a stressful week: what is theirs, what can move, what needs a conversation. Not medical advice.",
  },
  {
    id: "180",
    slug: "primary-foundations-evaluation",
    name: "Primary foundations evaluation",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "Evaluate early reading, writing and maths foundations from the evidence pasted.",
  },
  {
    id: "181",
    slug: "sar-handling-note",
    name: "SAR handling note",
    category: "Systems and compliance",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "A handling checklist and draft acknowledgement for a SAR. Remind them to involve DPO. Do not put personal data into the model if they can avoid it.",
  },
  {
    id: "182",
    slug: "subject-intent-statement",
    name: "Subject intent statement",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "A short subject intent that a teacher could defend. No 'we aim to inspire' padding.",
  },
  {
    id: "183",
    slug: "pupil-voice-questions",
    name: "Pupil-voice questions",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "Questions to check what pupils actually know and remember in a subject.",
  },
  {
    id: "184",
    slug: "subject-leader-plan",
    name: "Subject leader plan",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "A one-year subject plan. Monitoring that is light enough to happen.",
  },
  {
    id: "185",
    slug: "subject-resource-bid",
    name: "Subject resource bid",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "A short bid from a subject leader to SLT. Cost, pupils affected, what you will stop if this is funded.",
  },
  {
    id: "186",
    slug: "subject-leader-inspection-card",
    name: "Subject leader inspection card",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "A two-side crib for a subject leader. Intent, implementation, impact, weakest bit, what you are doing about it.",
  },
  {
    id: "187",
    slug: "support-staff-objectives",
    name: "Support staff objectives",
    category: "Staff and personnel",
    role: "a school leader dealing with staff",
    gate: false,
    guidance: [],
    job: "Appraisal objectives that fit the role. Observable, fair, not teacher-objectives pasted on.",
  },
  {
    id: "188",
    slug: "survey-question-set",
    name: "Survey question set",
    category: "Day to day",
    role: "a member of school staff",
    gate: false,
    guidance: [],
    job: "Write survey questions. Neutral. One idea each. Include how you will act on results.",
  },
  {
    id: "189",
    slug: "survey-write-up",
    name: "Survey write-up",
    category: "Governance",
    role: "someone preparing a paper for governors or trustees",
    gate: false,
    guidance: [],
    job: "Summarise pasted survey results for the board. Themes, outliers, recommended response.",
  },
  {
    id: "190",
    slug: "swot-into-actions",
    name: "SWOT into actions",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "Turn a SWOT into a small set of actions. Kill the decorative squares.",
  },
  {
    id: "191",
    slug: "teacher-appraisal-objectives",
    name: "Teacher appraisal objectives",
    category: "Staff and personnel",
    role: "a school leader dealing with staff",
    gate: false,
    guidance: [],
    job: "Draft teacher objectives linked to school priorities and the teacher's career stage.",
  },
  {
    id: "192",
    slug: "short-briefing",
    name: "Short briefing",
    category: "Day to day",
    role: "a member of school staff",
    gate: false,
    guidance: [],
    job: "Compress pasted text to the length asked. Keep names and numbers straight.",
  },
  {
    id: "193",
    slug: "leader-to-do-list",
    name: "Leader to-do list",
    category: "Day to day",
    role: "a member of school staff",
    gate: false,
    guidance: [],
    job: "Turn a dumped brain into a ordered list: today, this week, park, delegate.",
  },
  {
    id: "194",
    slug: "transition-support-plan",
    name: "Transition support plan",
    category: "Pupil support",
    role: "a pastoral lead",
    gate: false,
    guidance: [],
    job: "Plan a phase or school transition for a pupil or cohort.",
  },
  {
    id: "195",
    slug: "ucas-reference-draft",
    name: "UCAS reference draft",
    category: "Staff and personnel",
    role: "a school leader dealing with staff",
    gate: false,
    guidance: [],
    job: "Draft a UCAS reference from predicted grades and evidence supplied. Honest.",
  },
  {
    id: "196",
    slug: "vision-statement-options",
    name: "Vision statement options",
    category: "Communication",
    role: "a member of school staff",
    gate: false,
    guidance: [],
    job: "Offer a few vision options in the school's own language. Short enough to remember.",
  },
  {
    id: "197",
    slug: "external-visit-action-plan",
    name: "External visit action plan",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "Turn an adviser or inspector visit note into actions.",
  },
  {
    id: "198",
    slug: "school-web-page-copy",
    name: "School web page copy",
    category: "Communication",
    role: "a member of school staff",
    gate: false,
    guidance: [],
    job: "Write a web page. Scannable. No stock phrases. Include what a parent actually wants to know.",
  },
  {
    id: "199",
    slug: "workload-cut-list",
    name: "Workload cut list",
    category: "Staff and personnel",
    role: "a school leader dealing with staff",
    gate: false,
    guidance: [],
    job: "Propose specific things this school could stop, shrink or change, from the tasks the user lists.",
  },
  {
    id: "200",
    slug: "writing-moderation-notes",
    name: "Writing moderation notes",
    category: "School improvement",
    role: "a school leader",
    gate: false,
    guidance: [],
    job: "Help a moderation conversation from the pupil work descriptions supplied. Framework-aware if named.",
  },
  {
    id: "201",
    slug: "video-transcript-qanda",
    name: "Video transcript Q&A",
    category: "Day to day",
    role: "a member of school staff",
    gate: false,
    guidance: [],
    job: "The model cannot watch YouTube. Ask for a pasted transcript, then interrogate it.",
  }
];
