import type { DeskItem } from "./types";

// KS3 schemes and subject maps. Paste the programme of study or the school's own curriculum. Do not invent content.
export const deskItemsI: DeskItem[] = [
  {
    id: "445",
    slug: "three-year-ks3-scheme",
    name: "Three-year KS3 scheme",
    category: "KS3",
    job: "A Year 7 to Year 9 scheme from the pasted programme of study or the school's own curriculum. What must be secure by the end of Year 9. Do not smuggle GCSE topics in unless the school already does that and said so.",
  },
  {
    id: "446",
    slug: "two-year-ks3-scheme",
    name: "Two-year KS3 scheme",
    category: "KS3",
    job: "A Year 7 and Year 8 scheme when Year 9 starts the GCSE. What cannot be dropped. What Year 9 will still need if the GCSE assumes it. Build only from what the user pasted.",
  },
  {
    id: "447",
    slug: "year-7-scheme-from-pos",
    name: "Year 7 scheme",
    category: "KS3",
    job: "One year of Year 7 from the pasted curriculum. First half term that settles the class. Assessment points that are not mini-GCSEs. Homework a family can support without a textbook.",
  },
  {
    id: "448",
    slug: "year-8-scheme-from-pos",
    name: "Year 8 scheme",
    category: "KS3",
    job: "One year of Year 8 from the pasted curriculum. What Year 7 left unfinished if the user named it. Harder thinking, not just more content.",
  },
  {
    id: "449",
    slug: "year-9-scheme-from-pos",
    name: "Year 9 scheme",
    category: "KS3",
    job: "One year of Year 9 from the pasted curriculum. If this year is still KS3, keep it KS3. If the school has started the GCSE, say so and use the pasted spec instead.",
  },
  {
    id: "450",
    slug: "ks2-to-ks3-bridge",
    name: "KS2 to KS3 bridge",
    category: "KS3",
    job: "A first half term that uses the KS2 information the user pasted. Reading ages, what they can already do, what Year 6 did not finish. No invented SATs scores.",
  },
  {
    id: "451",
    slug: "mixed-ability-ks3-scheme",
    name: "Mixed-ability KS3 scheme",
    category: "KS3",
    job: "A scheme for a mixed-ability KS3 class. Core and stretch in the same sequence. Support that is not a different curriculum in disguise.",
  },
  {
    id: "452",
    slug: "ks3-assessment-calendar",
    name: "KS3 assessment calendar",
    category: "KS3",
    job: "An assessment calendar for the key stage. What each checkpoint actually samples from the pasted curriculum. No fake GCSE grades unless the school already uses them and the user said so.",
  },
  {
    id: "453",
    slug: "ks3-retrieval-spine",
    name: "KS3 retrieval spine",
    category: "KS3",
    job: "A retrieval spine across Years 7 to 9 from the pasted curriculum. What returns in the next year. Do not add extra facts.",
  },
  {
    id: "454",
    slug: "ks3-homework-cycle",
    name: "KS3 homework cycle",
    category: "KS3",
    job: "A half-term homework cycle. Short. Retrieval or practice. Work that does not need a specialist adult or a printer.",
  },
  {
    id: "455",
    slug: "ks3-catch-up-literacy",
    name: "KS3 catch-up literacy",
    category: "KS3",
    job: "A catch-up plan from the reading or writing evidence the user pasted. Minutes per week as given. Phonics or fluency only if that is what the data points to. No invented reading ages.",
  },
  {
    id: "456",
    slug: "ks3-catch-up-numeracy",
    name: "KS3 catch-up numeracy",
    category: "KS3",
    job: "A catch-up plan from the number gaps the user listed. Secure the prerequisites before the Year 8 or Year 9 topic that needs them.",
  },
  {
    id: "457",
    slug: "options-evening-year-9",
    name: "Options evening brief",
    category: "KS3",
    job: "A parent and pupil brief for Year 8 or Year 9 options. What this school actually offers. EBacc only if the school uses that language. No career fortune-telling.",
  },
  {
    id: "458",
    slug: "ks3-to-gcse-handover",
    name: "KS3 to GCSE handover",
    category: "KS3",
    job: "A handover note from the KS3 teacher to the GCSE teacher. What is secure, what was skimmed, who will struggle with the first unit. Facts only.",
  },
  {
    id: "459",
    slug: "ks3-knowledge-organiser",
    name: "KS3 knowledge organiser",
    category: "KS3",
    job: "A one-page organiser for the unit named, from the pasted curriculum only. Definitions and must-know items. No extra GCSE content dressed up as stretch.",
  },
  {
    id: "460",
    slug: "ks3-enquiry-or-unit",
    name: "KS3 enquiry or unit",
    category: "KS3",
    job: "One unit or enquiry from the question the user named. Lessons that fit the periods given. Outcome that a Year 7 or Year 8 can actually produce.",
  },
  {
    id: "461",
    slug: "ks3-english-map",
    name: "KS3 English map",
    category: "KS3",
    job: "A KS3 English map from the pasted programme of study and the texts the school actually teaches. Reading, writing, oracy. Do not invent a set text list.",
  },
  {
    id: "462",
    slug: "ks3-maths-map",
    name: "KS3 Maths map",
    category: "KS3",
    job: "A KS3 Maths map from the pasted programme of study. Number, algebra, geometry, ratio, probability, statistics in an order this department can teach. Gaps from KS2 only if listed.",
  },
  {
    id: "463",
    slug: "ks3-science-map",
    name: "KS3 Science map",
    category: "KS3",
    job: "A KS3 Science map from the pasted programme of study. Biology, chemistry, physics. Working scientifically. Practicals only if the department named the equipment they have.",
  },
  {
    id: "464",
    slug: "ks3-history-map",
    name: "KS3 History map",
    category: "KS3",
    job: "A KS3 History map from the pasted programme of study and the enquiries this department teaches. Chronology across the key stage. No extra periods.",
  },
  {
    id: "465",
    slug: "ks3-geography-map",
    name: "KS3 Geography map",
    category: "KS3",
    job: "A KS3 Geography map from the pasted programme of study. Locational knowledge, places, human and physical, fieldwork only if the school named the sites.",
  },
  {
    id: "466",
    slug: "ks3-mfl-map",
    name: "KS3 language map",
    category: "KS3",
    job: "A KS3 map for the language named. Phonics, vocabulary, grammar from the lists or scheme the user pasted. Do not invent a word list.",
  },
  {
    id: "467",
    slug: "ks3-computing-map",
    name: "KS3 Computing map",
    category: "KS3",
    job: "A KS3 Computing map from the pasted programme of study. Computer science, IT and digital literacy as the school splits them. Software only if named.",
  },
  {
    id: "468",
    slug: "ks3-dt-map",
    name: "KS3 Design and Technology map",
    category: "KS3",
    job: "A KS3 D and T map from the pasted programme of study and the materials this workshop actually uses. Cooking and nutrition if that sits here.",
  },
  {
    id: "469",
    slug: "ks3-art-map",
    name: "KS3 Art and Design map",
    category: "KS3",
    job: "A KS3 Art map from the pasted curriculum. Disciplines this department teaches. Artists only if the user named them.",
  },
  {
    id: "470",
    slug: "ks3-music-map",
    name: "KS3 Music map",
    category: "KS3",
    job: "A KS3 Music map from the pasted curriculum. Performing, composing, listening. Instruments and software only if the school has them.",
  },
  {
    id: "471",
    slug: "ks3-pe-map",
    name: "KS3 PE map",
    category: "KS3",
    job: "A KS3 PE map from the pasted programme of study and the sports this site can actually run. Indoor backup. No invented fixtures.",
  },
  {
    id: "472",
    slug: "ks3-citizenship-map",
    name: "KS3 Citizenship map",
    category: "KS3",
    job: "A KS3 Citizenship map from the pasted programme of study. Politics, law, media, volunteering as the document sets them. No party line.",
  },
  {
    id: "473",
    slug: "ks3-re-map",
    name: "KS3 RE map",
    category: "KS3",
    job: "A KS3 RE map from the locally agreed syllabus or the academy curriculum the user pasted. Religions and worldviews only as listed. Do not invent beliefs.",
  },
  {
    id: "474",
    slug: "ks3-drama-oracy-map",
    name: "KS3 Drama or oracy map",
    category: "KS3",
    job: "A KS3 Drama or oracy map from what the school actually teaches. If drama sits inside English, say so. Texts and productions only if named.",
  },
  {
    id: "475",
    slug: "ks3-rse-health-map",
    name: "KS3 RSE and health map",
    category: "KS3",
    job: "A map for relationships, sex and health education from the school's policy and the statutory content the user pasted. Age-appropriate. Right to withdraw flagged where it applies. Not a biology lesson in disguise unless that is the slot.",
  },
  {
    id: "476",
    slug: "ks3-reading-across-subjects",
    name: "Reading across KS3 subjects",
    category: "KS3",
    job: "How subjects other than English will teach reading of their own texts, from the approach the school named. Vocabulary and a short text type per subject if listed.",
  },
  {
    id: "477",
    slug: "ks3-writing-across-subjects",
    name: "Writing across KS3 subjects",
    category: "KS3",
    job: "How subjects will get writing done without turning every book into an English exercise. Sentence-level habits if the school uses them.",
  },
  {
    id: "478",
    slug: "ks3-cover-proof-scheme",
    name: "KS3 cover-proof scheme",
    category: "KS3",
    job: "Rewrite a KS3 scheme so a cover supervisor can run the desk lessons. Flag practicals, performances and anything that must not run without the specialist.",
  },
  {
    id: "479",
    slug: "ks3-send-in-the-scheme",
    name: "SEND in the KS3 scheme",
    category: "KS3",
    job: "Adapt a pasted KS3 scheme for the needs listed. Same curriculum. Access, not a parallel course. No invented diagnoses.",
  },
  {
    id: "480",
    slug: "year-7-settling-curriculum",
    name: "Year 7 settling curriculum",
    category: "KS3",
    job: "The first three weeks in this subject. Routines, how books work, one early win. Content from the pasted Year 7 unit only.",
  },
  {
    id: "481",
    slug: "ks3-moderation-pack",
    name: "KS3 moderation pack",
    category: "KS3",
    job: "A moderation pack for a KS3 assessment the department already uses. What good looks like from the criteria pasted. No invented grade descriptors.",
  },
  {
    id: "482",
    slug: "ks3-parents-curriculum-note",
    name: "KS3 curriculum note for parents",
    category: "KS3",
    job: "A plain note for families on what this year of the subject covers and how they can help at home. No shopping list of revision guides.",
  },
  {
    id: "483",
    slug: "ks3-more-able-stretch",
    name: "KS3 stretch without early GCSE",
    category: "KS3",
    job: "Stretch for pupils who are ready for harder thinking in this subject. Depth and disciplinary habit, not a Year 10 booklet in Year 8, unless the user asked for that and pasted the spec.",
  },
  {
    id: "484",
    slug: "ks3-practical-or-fieldwork-calendar",
    name: "KS3 practical or fieldwork calendar",
    category: "KS3",
    job: "A calendar of practicals, performances or fieldwork from what the department can actually staff and fund. Risk checks the user must confirm.",
  },
  {
    id: "485",
    slug: "ks3-interleaved-year",
    name: "KS3 interleaved year",
    category: "KS3",
    job: "Two versions of a KS3 year from the same pasted curriculum: blocked, then interleaved. The teacher picks one.",
  },
  {
    id: "486",
    slug: "ks3-tutor-curriculum-slot",
    name: "KS3 tutor curriculum slot",
    category: "KS3",
    job: "A 15 minute tutor slot that supports this subject's retrieval. A non-specialist can run it. Cards only from what the user pastes.",
  },
  {
    id: "487",
    slug: "ks3-end-of-year-exam-design",
    name: "KS3 end-of-year exam design",
    category: "KS3",
    job: "A structure for an end-of-year exam from the year's curriculum. What it should sample. Timing. Do not write a fake paper unless they asked and supplied the content.",
  },
  {
    id: "488",
    slug: "ks3-report-comment-bank",
    name: "KS3 report comment bank",
    category: "KS3",
    job: "A short comment bank for this subject at KS3. Strength, next step, how to help at home. No invented pupils. Teacher still picks the line.",
  },
  {
    id: "489",
    slug: "ks3-department-intent",
    name: "KS3 department intent",
    category: "KS3",
    job: "A one-page intent for this subject at KS3 from what the department already believes and the programme of study pasted. Plain English. Not an Ofsted performance.",
  },
  {
    id: "490",
    slug: "ks3-any-subject-fallback",
    name: "Any other KS3 subject",
    category: "KS3",
    job: "A scheme and unit map for a KS3 subject the shelf does not name. Build only from the pasted curriculum. If they did not paste one, stop and ask.",
  },
];
