import type { DeskItem } from "./types";

export const deskItemsB: DeskItem[] = [
  {
    id: "071",
    slug: "finance-benchmark-note",
    name: "Finance benchmark note",
    category: "Governance",
    job: "Explain pasted benchmark figures in plain English for governors. Do not invent ICFP or CFR numbers.",
  },
  {
    id: "072",
    slug: "new-head-100-day-plan",
    name: "New head 100-day plan",
    category: "For you",
    job: "Build a first 100 days plan. Listening first. No fake 'quick wins' that wreck trust.",
  },
  {
    id: "073",
    slug: "flexible-working-reply",
    name: "Flexible working reply",
    category: "Staff and personnel",
    job: "Help draft a lawful, human response to a flexible working request from the facts given. Not legal advice.",
  },
  {
    id: "074",
    slug: "foi-or-sar-holding-reply",
    name: "FOI or SAR holding reply",
    category: "Systems and compliance",
    job: "Draft a holding or response letter. Remind the user of statutory timescales they must check. Do not disclose personal data in the draft.",
  },
  {
    id: "075",
    slug: "fundraising-calendar",
    name: "Fundraising calendar",
    category: "Day to day",
    job: "Plan a term of fundraising the PTA and office can run without burning people out.",
  },
  {
    id: "076",
    slug: "gatsby-benchmark-plan",
    name: "Gatsby benchmark plan",
    category: "School improvement",
    job: "Map current careers work to Gatsby benchmarks using only what the school already does, then gaps.",
  },
  {
    id: "077",
    slug: "board-effectiveness-plan",
    name: "Board effectiveness plan",
    category: "Governance",
    job: "Turn a governance self-review into a small, dated action plan.",
  },
  {
    id: "078",
    slug: "minutes-pattern-note",
    name: "Minutes pattern note",
    category: "Governance",
    job: "Read pasted minutes. List decisions, deferred items, missing follow-up, questions the board keeps not asking.",
  },
  {
    id: "079",
    slug: "governor-bio",
    name: "Governor bio",
    category: "Governance",
    job: "Write a short public bio from the facts the governor supplied. No padding.",
  },
  {
    id: "080",
    slug: "monitoring-visit-plan",
    name: "Monitoring visit plan",
    category: "Governance",
    job: "Plan a focused governor visit linked to the SIP priority named. Questions, evidence, what not to do.",
  },
  {
    id: "081",
    slug: "monitoring-visit-report",
    name: "Monitoring visit report",
    category: "Governance",
    job: "Write a visit report from notes. What was seen, link to SIP, questions for the next meeting. Not an inspection.",
  },
  {
    id: "082",
    slug: "board-question-bank",
    name: "Board question bank",
    category: "Governance",
    job: "Write sharp governing questions for the paper or priority named. Open questions. No gotchas.",
  },
  {
    id: "083",
    slug: "committee-paper-draft",
    name: "Committee paper draft",
    category: "Governance",
    job: "Draft a committee or board paper. Purpose, evidence, options, the decision needed.",
  },
  {
    id: "084",
    slug: "role-description-for-a-governor",
    name: "Role description for a governor",
    category: "Governance",
    job: "Plain-English role summary for a specific link or committee role.",
  },
  {
    id: "085",
    slug: "board-strategy-page",
    name: "Board strategy page",
    category: "Governance",
    job: "Write the board's strategic page: core functions, how they will know, what they will not do.",
  },
  {
    id: "086",
    slug: "grievance-process-note",
    name: "Grievance process note",
    category: "Staff and personnel",
    job: "Explain the next process step from the school's policy. Do not take sides. Not legal advice.",
  },
  {
    id: "087",
    slug: "headteacher-pm-agenda",
    name: "Headteacher PM agenda",
    category: "Governance",
    job: "Draft a PM panel agenda and evidence list from the objectives supplied.",
  },
  {
    id: "088",
    slug: "headteacher-pm-report-skeleton",
    name: "Headteacher PM report skeleton",
    category: "Governance",
    job: "Skeleton a PM report. Objectives, evidence, remaining questions. The panel writes the judgement.",
  },
  {
    id: "089",
    slug: "heads-report-comments",
    name: "Head's report comments",
    category: "Communication",
    job: "Write a bank of head's comments from notes on the pupil. No empty praise. Age-appropriate.",
  },
  {
    id: "090",
    slug: "full-heads-pupil-comment",
    name: "Full head's pupil comment",
    category: "Communication",
    job: "Write one full report comment from the teacher's notes pasted.",
  },
  {
    id: "091",
    slug: "headteachers-report-draft",
    name: "Headteacher's report draft",
    category: "Governance",
    job: "Draft a headteacher report to governors from the bullets supplied. Data first. Risks honest.",
  },
  {
    id: "092",
    slug: "idsr-in-plain-english",
    name: "IDSR in plain English",
    category: "School improvement",
    job: "Explain pasted IDSR or similar inspection data for staff or governors. Do not invent significance.",
  },
  {
    id: "093",
    slug: "impact-statement",
    name: "Impact statement",
    category: "School improvement",
    job: "Write an impact statement that separates activity from effect. Only claim what the evidence shows.",
  },
  {
    id: "094",
    slug: "implementation-plan",
    name: "Implementation plan",
    category: "School improvement",
    job: "Use a simple implement-first structure: what, who, when, how you will know, what you will stop.",
  },
  {
    id: "095",
    slug: "inclusion-strategy-draft",
    name: "Inclusion strategy draft",
    category: "SEND and inclusion",
    job: "Draft an inclusion strategy this school can staff. Universal, targeted, specialist.",
  },
  {
    id: "096",
    slug: "staff-briefing-note",
    name: "Staff briefing note",
    category: "Communication",
    job: "Write a Monday briefing or internal update. Short. What to do.",
  },
  {
    id: "097",
    slug: "interview-question-set",
    name: "Interview question set",
    category: "Staff and personnel",
    job: "Write questions and what good answers show, tied to the person spec. Include a safeguarding question.",
  },
  {
    id: "098",
    slug: "interview-task-design",
    name: "Interview task design",
    category: "Staff and personnel",
    job: "Design a fair interview task. Time, materials, criteria, how it will be scored.",
  },
  {
    id: "099",
    slug: "investigation-summary",
    name: "Investigation summary",
    category: "Staff and personnel",
    job: "Summarise investigation papers the user pastes. Facts / disputed / still unknown. No verdict.",
  },
  {
    id: "100",
    slug: "job-advert",
    name: "Job advert",
    category: "Staff and personnel",
    job: "Write a job advert people will finish reading. Honest about the school. Inclusive language.",
  },
  {
    id: "101",
    slug: "job-description-draft",
    name: "Job description draft",
    category: "Staff and personnel",
    job: "Draft a JD and person spec. Essential vs desirable. No impossible wish list.",
  },
  {
    id: "102",
    slug: "advent-kindness-calendar",
    name: "Advent kindness calendar",
    category: "Day to day",
    job: "Build a 24-day kindness calendar that fits a school day and this school's values.",
  },
  {
    id: "103",
    slug: "ks2-outcomes-note",
    name: "KS2 outcomes note",
    category: "School improvement",
    job: "Explain pasted KS2 figures. Groups, trends, questions for subject leaders. No fake national comparisons.",
  },
  {
    id: "104",
    slug: "learning-walk-follow-up",
    name: "Learning walk follow-up",
    category: "School improvement",
    job: "Turn walk notes into a small action plan. Three things, not thirty.",
  },
  {
    id: "105",
    slug: "learning-walk-plan",
    name: "Learning walk plan",
    category: "School improvement",
    job: "Plan a walk with a single focus. What you will look at, questions, how feedback returns to staff.",
  },
  {
    id: "106",
    slug: "observation-feedback",
    name: "Observation feedback",
    category: "Staff and personnel",
    job: "Write observation feedback from notes. Specific, developmental, no Ofsted-grade language unless asked.",
  },
  {
    id: "107",
    slug: "observation-form",
    name: "Observation form",
    category: "Staff and personnel",
    job: "Design a short observation form matched to the school's teaching principles.",
  },
  {
    id: "108",
    slug: "reply-to-a-letter",
    name: "Reply to a letter",
    category: "Communication",
    job: "Reply to the pasted letter. Answer each point. Say what you will do.",
  },
  {
    id: "109",
    slug: "formal-school-letter",
    name: "Formal school letter",
    category: "Communication",
    job: "Write a formal letter. Address, date, reference, purpose, close.",
  },
  {
    id: "110",
    slug: "school-marketing-plan",
    name: "School marketing plan",
    category: "Communication",
    job: "A modest, honest plan for how this school tells its story. No growth-hacking.",
  },
  {
    id: "111",
    slug: "minutes-from-notes",
    name: "Minutes from notes",
    category: "Day to day",
    job: "Turn rough notes into minutes: decisions, actions, owners, dates.",
  },
  {
    id: "112",
    slug: "mou-first-draft",
    name: "MoU first draft",
    category: "Systems and compliance",
    job: "Draft an MoU skeleton. Mark every clause that needs a solicitor or trust lawyer.",
  },
  {
    id: "113",
    slug: "monitoring-follow-up-note",
    name: "Monitoring follow-up note",
    category: "School improvement",
    job: "Write what happens after monitoring: who does what by when, how it will be checked.",
  },
  {
    id: "114",
    slug: "annual-monitoring-calendar",
    name: "Annual monitoring calendar",
    category: "School improvement",
    job: "Build a monitoring calendar that does not crush staff. Map it to SIP priorities.",
  },
  {
    id: "115",
    slug: "music-development-plan",
    name: "Music development plan",
    category: "School improvement",
    job: "Draft a music development plan from current provision the user lists.",
  },
  {
    id: "116",
    slug: "family-newsletter",
    name: "Family newsletter",
    category: "Communication",
    job: "Write a newsletter section or full draft. Human. Dates accurate only if supplied.",
  },
  {
    id: "117",
    slug: "notes-into-a-paper",
    name: "Notes into a paper",
    category: "Day to day",
    job: "Turn messy notes into a clean paper of the type asked for.",
  },
  {
    id: "118",
    slug: "npq-assessment-notes",
    name: "NPQ assessment notes",
    category: "For you",
    job: "Help a colleague map evidence to the NPQ framework they name. Do not write the assessment for them as if it were their voice.",
  },
  {
    id: "119",
    slug: "inspection-framework-mapping",
    name: "Inspection framework mapping",
    category: "School improvement",
    job: "Map the school's evidence to the inspection framework the user names. No predicted grade.",
  },
  {
    id: "120",
    slug: "evidence-pile-sort",
    name: "Evidence pile sort",
    category: "School improvement",
    job: "Sort pasted evidence under inspection areas. Say what is thin.",
  },
  {
    id: "121",
    slug: "inspection-call-brief",
    name: "Inspection call brief",
    category: "School improvement",
    job: "Prepare the head for an initial inspection call from the facts they have. Questions, data to have to hand.",
  },
  {
    id: "122",
    slug: "sip-from-inspection-findings",
    name: "SIP from inspection findings",
    category: "School improvement",
    job: "Turn inspection findings the user pastes into SIP priorities. Keep the inspector's wording visible.",
  },
  {
    id: "123",
    slug: "parent-message-pack",
    name: "Parent message pack",
    category: "Communication",
    job: "Write the parent communication for the event or issue named. Anticipate the question underneath the question.",
  },
  {
    id: "124",
    slug: "parent-support-script",
    name: "Parent support script",
    category: "Pupil support",
    job: "Help a leader prepare a supportive conversation with a parent. Practical next steps.",
  },
  {
    id: "125",
    slug: "parent-view-themes",
    name: "Parent View themes",
    category: "Governance",
    job: "Summarise pasted Parent View or survey comments into themes and a board note.",
  },
  {
    id: "126",
    slug: "family-engagement-ideas",
    name: "Family engagement ideas",
    category: "Communication",
    job: "Suggest engagement ideas this school can run with the staff time they actually have.",
  },
  {
    id: "127",
    slug: "pastoral-support-plan",
    name: "Pastoral support plan",
    category: "Pupil support",
    job: "Draft a pastoral plan. Safety first. Review date. Named adult.",
  },
  {
    id: "128",
    slug: "pupil-personal-development-plan",
    name: "Pupil personal development plan",
    category: "Pupil support",
    job: "Plan personal development work for a pupil or cohort from the goals given.",
  },
  {
    id: "129",
    slug: "peep-draft",
    name: "PEEP draft",
    category: "Systems and compliance",
    job: "Draft a PEEP from the person's needs as described. Do not guess mobility or medical detail.",
  },
  {
    id: "130",
    slug: "personal-statement-critique",
    name: "Personal statement critique",
    category: "Staff and personnel",
    job: "Critique a job or NPQ personal statement. What to cut, what is missing, what sounds generic.",
  },
  {
    id: "131",
    slug: "phased-return-plan",
    name: "Phased return plan",
    category: "Staff and personnel",
    job: "Draft a phased return to work plan from occupational health and staff wishes as supplied.",
  },
  {
    id: "132",
    slug: "policy-first-draft",
    name: "Policy first draft",
    category: "Systems and compliance",
    job: "Draft or refresh a policy from the model and local detail the user pastes. List statutory checks they must do.",
  },
  {
    id: "133",
    slug: "slide-outline",
    name: "Slide outline",
    category: "Day to day",
    job: "Produce a slide-by-slide outline with speaker notes. Short titles. One idea a slide.",
  },
  {
    id: "134",
    slug: "school-press-note",
    name: "School press note",
    category: "Communication",
    job: "Write a press note. Newsworthy first sentence. Quote only if the user supplied one.",
  },
  {
    id: "135",
    slug: "prevent-risk-assessment",
    name: "Prevent risk assessment",
    category: "Systems and compliance",
    job: "Draft a Prevent risk assessment from local context the user describes. Serious, specific, not a copied list.",
  },
  {
    id: "136",
    slug: "staff-procedure",
    name: "Staff procedure",
    category: "Day to day",
    job: "Write a procedure as numbered steps. Who, when, what 'done' looks like.",
  },
  {
    id: "137",
    slug: "staff-pd-plan",
    name: "Staff PD plan",
    category: "Staff and personnel",
    job: "Build a PD plan from appraisal objectives and school priorities. Include time, not just courses.",
  },
  {
    id: "138",
    slug: "blank-proforma",
    name: "Blank proforma",
    category: "Day to day",
    job: "Design a one-page form with prompts. Leave space to write.",
  },
  {
    id: "139",
    slug: "new-pupil-induction",
    name: "New pupil induction",
    category: "Pupil support",
    job: "Plan the first days and first term for a new pupil, including mid-year joiners.",
  },
  {
    id: "140",
    slug: "pupil-premium-strategy-draft",
    name: "Pupil premium strategy draft",
    category: "School improvement",
    job: "Draft a pupil premium strategy from the school's barriers and evidence. Align to the DfE template headings if the user asks. No fake EEF citations.",
  }
];
